### ISSUE TITLE
wds执行hiveSQL语句报错，初始化引擎失败

### ISSUE THREAD

**Issue by chenshixiongz** [apache/incubator-linkis#1204]
SQL语句：select count(*) from sdgh_dwd.dwd_account_year
web界面报错信息：
ERROR Task is Failed,errorMsg: errCode: 12003 ,desc: bigdata19:9101_8 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, bigdata19:11192) ticketID:d5e808b3-b9ec-48b2-99db-358bd9eaee5d 初始化引擎失败,原因: Failed to start EngineConn, reason: ECMErrorException: errCode: 10000 ,desc: Failed to init DefaultEngineConn(ShuttingDown, d5e808b3-b9ec-48b2-99db-358bd9eaee5d, com.webank.wedatasphere.linkis.manager.engineplugin.common.resource.UserNodeResource@5227c1f7, [[key: userCreator, value: {"creator":"IDE","user":"hdfs"}, str: hdfs-IDE], [key: engineType, value: {"engineType":"hive","version":"2.1.1"}, str: hive-2.1.1]], EngineConnCreationDescImpl(null,null,{wds.linkis.rm.yarnqueue.memory.max=300G, hive.client.java.opts=, wds.linkis.rm.client.core.max=10, mapred.reduce.tasks=10, hive.exec.reduce.bytes.per.reducer=10, wds.linkis.rm.instance=10, wds.linkis.rm.yarnqueue.instance.max=30, wds.linkis.engineconn.java.driver.memory=2g, wds.linkis.rm.yarnqueue.cores.max=150, dfs.block.size=10, wds.linkis.rm.client.memory.max=20G, wds.linkis.rm.yarnqueue=default}), com.webank.wedatasphere.linkis.ecm.core.engineconn.EngineConnInfo@26beb8ba, null, com.webank.wedatasphere.linkis.ecm.core.launch.EngineConnLaunchRunnerImpl@63bf530a, ServiceInstance(linkis-cg-engineconn, bigdata19:11192), null), status shutting down ,ip: bigdata19 ,port: 9102 ,serviceKind: linkis-cg-engineconnmanager

log日志内容;

Exception in thread "main" java.lang.NullPointerException
        at com.webank.wedatasphere.linkis.rpc.sender.SpringCloudFeignConfigurationCache$.getClient(SpringCloudFeignConfigurationCache.scala:73)
        at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender.doBuilder(SpringMVCRPCSender.scala:49)
        at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.newRPC(BaseRPCSender.scala:67)
        at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.com$webank$wedatasphere$linkis$rpc$BaseRPCSender$$getRPC(BaseRPCSender.scala:54)
        at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.send(BaseRPCSender.scala:105)
        at com.webank.wedatasphere.linkis.engineconn.callback.service.AbstractEngineConnStartUpCallback.callback(EngineConnCallback.scala:39)
        at com.webank.wedatasphere.linkis.engineconn.callback.hook.CallbackEngineConnHook.afterEngineServerStartFailed(CallbackEngineConnHook.scala:63)
        at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer$$anonfun$main$15.apply(EngineConnServer.scala:64)
        at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer$$anonfun$main$15.apply(EngineConnServer.scala:64)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:64)
        at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala)

求解

**Comment by peacewong** [comment]
Hello, is there any other error log on this npe
