### ISSUE TITLE
NoClassDefFoundError: com/webank/wedatasphere/linkis/LinkisBaseServerApp

### ISSUE THREAD

**Issue by 475350551** [apache/incubator-linkis#1236]
根据部署教程，无法启动linkis，

1. 配置vi config/linkis-env.sh，不依赖hdfs，并成功执行sh bin/install.sh，然后执行sh sbin/linkis-start-all.sh失败
2.  error如下：
Begin to check ps-publicservice
Is local execution:sh /opt/linkis/inst/LinkisInstall/sbin/linkis-daemon.sh status ps-publicservice
server ps-publicservice is not running
ERROR: your linkis-ps-publicservice microservice is not start successful !!! ERROR logs as follows :
Please check  detail log, log path :/opt/linkis/inst/LinkisInstall/logs/linkis-ps-publicservice.log
<---------------------------------------------------->
Is remote execution:tail -n 50 /opt/linkis/inst/LinkisInstall/logs/linkis-ps-publicservice.log
Bad port 'linkis-ps-publicservice'
<---------------------------------------------------->
Please check  detail log, log path :/opt/linkis/inst/LinkisInstall/logs/linkis-ps-publicservice.log

3. 检查日志发现：
Exception in thread "main" java.lang.NoClassDefFoundError: com/webank/wedatasphere/linkis/LinkisBaseServerApp
	at com.webank.wedatasphere.linkis.jobhistory.LinkisPublicServiceApp.main(LinkisPublicServiceApp.java:24)
Caused by: java.lang.ClassNotFoundException: com.webank.wedatasphere.linkis.LinkisBaseServerApp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

**Comment by peacewong** [comment]
This needs to check if there is a jar of linkis-module under lib/linkis-commons/public-module/
