### ISSUE TITLE
[Bug]  Shell、Spark等引擎无法执行

### ISSUE THREAD

**Issue by shenbinglife** [apache/incubator-linkis#1429]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnManager

### What happened + What you expected to happen

Linkis 1.0.2
![image](https://user-images.githubusercontent.com/16119667/153402178-5ce250ec-8ca3-476f-96f6-3547f6d39503.png)

2022-02-10 19:19:40.019 ERROR Task is Failed,errorMsg: errCode: 12003 ,desc: hadoop01:9101_20 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, hadoop01:42750) ticketID:fcffa5b7-1bae-4b5b-8e9b-9ed439d28258 初始化引擎失败,原因: Failed to start EngineConn, reason: ECMErrorException: errCode: 10000 ,desc: Failed to init DefaultEngineConn(ShuttingDown, fcffa5b7-1bae-4b5b-8e9b-9ed439d28258, com.webank.wedatasphere.linkis.manager.engineplugin.common.resource.UserNodeResource@34f1350b, [[key: userCreator, value: {"creator":"IDE","user":"hive"}, str: hive-IDE], [key: engineType, value: {"engineType":"shell","version":"1"}, str: shell-1]], EngineConnCreationDescImpl(null,null,{wds.linkis.rm.yarnqueue.memory.max=300G, wds.linkis.rm.client.core.max=10, wds.linkis.rm.instance=10, wds.linkis.rm.yarnqueue.instance.max=30, wds.linkis.rm.yarnqueue.cores.max=150, wds.linkis.rm.client.memory.max=20G, wds.linkis.rm.yarnqueue=optkrill}), com.webank.wedatasphere.linkis.ecm.core.engineconn.EngineConnInfo@71f3adf1, null, com.webank.wedatasphere.linkis.ecm.core.launch.EngineConnLaunchRunnerImpl@57dcf32, ServiceInstance(linkis-cg-engineconn, hadoop01:42750), null), status shutting down ,ip: hadoop01 ,port: 9102 ,serviceKind: linkis-cg-engineconnmanager

### Relevent platform

Linkis 1.0.2

### Reproduction script

echo 'hello world'

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
You can check whether there is any exception information in the entrance/linkismanager log files

**Comment by gongzh021** [comment]
大佬，我遇到了和类似的问题，能帮我看看吗，报错如下：
2022-04-08 19:03:55.302 [INFO ] [AskEngineService-Thread-41              ] o.a.l.m.a.s.e.DefaultEngineCreateService (41) [info] - Start to create Engine for request: EngineCreateRequest{labels={userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3}, timeOut=660000, user='root', createService='dssmark_id: mark_0', description='null'}.
2022-04-08 19:03:55.311 [INFO ] [AskEngineService-Thread-42              ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (123) [apply] - Failed  to async(iZbp14j2amyqhhwlqedv5kZ:9101_20) createEngine, can Retry true org.apache.linkis.common.exception.LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3} not found ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager
        at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.scala:177) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:94) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:84) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

2022-04-08 19:03:55.411 [INFO ] [RpcMessageScheduler-ThreadPool-40       ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (60) [askEngine] - received engineAskRequest EngineAskRequest{labels={userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3}, timeOut=660000, user='root', createService='dssmark_id: mark_0', description='null'}
2022-04-08 19:03:55.412 [INFO ] [RpcMessageScheduler-ThreadPool-40       ] o.a.l.m.a.s.e.DefaultEngineReuseService (41) [info] - Start to reuse Engine for request: EngineReuseRequest{timeOut=660000, reuseCount=0, user='root'}
2022-04-08 19:03:55.422 [WARN ] [RpcMessageScheduler-ThreadPool-40       ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (71) [apply] - user root reuse engine failed errCode: 30001 ,desc: No engine can be reused, cause from db is null ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager
2022-04-08 19:03:55.423 [INFO ] [AskEngineService-Thread-43              ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (85) [apply] - Start to async(iZbp14j2amyqhhwlqedv5kZ:9101_21) createEngine, dssmark_id: mark_0
2022-04-08 19:03:55.423 [INFO ] [AskEngineService-Thread-43              ] o.a.l.m.a.s.e.DefaultEngineCreateService (41) [info] - Start to create Engine for request: EngineCreateRequest{labels={userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3}, timeOut=660000, user='root', createService='dssmark_id: mark_0', description='null'}.
2022-04-08 19:03:55.432 [INFO ] [AskEngineService-Thread-44              ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (123) [apply] - Failed  to async(iZbp14j2amyqhhwlqedv5kZ:9101_21) createEngine, can Retry true org.apache.linkis.common.exception.LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3} not found ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager
        at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.scala:177) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:94) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:84) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

2022-04-08 19:04:23.581 [INFO ] [RpcMessageScheduler-ThreadPool-41       ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 19:04:23.587 [WARN ] [RpcMessageScheduler-ThreadPool-41       ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
2022-04-08 19:04:39.958 [INFO ] [Linkis-Default-Scheduler-Thread-3       ] o.a.l.m.a.s.m.NodeHeartbeatMonitor (41) [info] - Start to check the health of the node
2022-04-08 19:04:39.962 [INFO ] [Linkis-Default-Scheduler-Thread-3       ] o.a.l.m.a.s.m.NodeHeartbeatMonitor (41) [info] - Finished to check the health of the node
2022-04-08 19:04:53.577 [INFO ] [RpcMessageScheduler-ThreadPool-42       ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 19:04:53.582 [WARN ] [RpcMessageScheduler-ThreadPool-42       ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
2022-04-08 19:05:23.577 [INFO ] [RpcMessageScheduler-ThreadPool-43       ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 19:05:23.582 [WARN ] [RpcMessageScheduler-ThreadPool-43       ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
2022-04-08 19:05:53.577 [INFO ] [RpcMessageScheduler-ThreadPool-44       ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 19:05:53.581 [WARN ] [RpcMessageScheduler-ThreadPool-44       ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
