### ISSUE TITLE
linkis适配Hadoop3.1.1，编译成功，linkis-cg-engineconnmanager启动失败。

### ISSUE THREAD

**Issue by breeze1126** [apache/incubator-linkis#1458]
2022-02-14 15:30:47.363 [INFO ] [main                                    ] o.a.l.c.c.BDPConfiguration$ (41) [info] - ******************************** Info: The Linkis read linkis.properties file from file:/data/dss/LinkisInstall/conf/linkis.properties ！***************************
2022-02-14 15:30:47.370 [INFO ] [main                                    ] o.a.l.c.c.BDPConfiguration$ (41) [info] - ******************************** Info: The Linkis read linkis-cg-engineconnmanager.properties file from file:/data/dss/LinkisInstall/conf/linkis-cg-engineconnmanager.properties ！***************************
2022-02-14 15:30:47.433 [INFO ] [main                                    ] o.a.l.LinkisBaseServerApp (48) [main] - Ready to start linkis-cg-engineconnmanager with args: --spring.profiles.active=linkis
--spring.mvc.servlet.path=/api/rest_j/v1
--spring.servlet.multipart.max-file-size=500MB
--spring.servlet.multipart.file-size-threshold=50MB
--spring.servlet.multipart.max-request-size=500MB
--server.port=9102
--application.name=linkis-cg-engineconnmanager.
2022-02-14 15:30:48.612 [INFO ] [main                                    ] o.s.c.c.c.ConfigServicePropertySourceLocator (249) [getRemoteEnvironment] - Fetching config from server at : http://localhost:8888
2022-02-14 15:30:48.747 [INFO ] [main                                    ] o.s.c.c.c.ConfigServicePropertySourceLocator (273) [getRemoteEnvironment] - Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
2022-02-14 15:30:48.748 [WARN ] [main                                    ] o.s.c.c.c.ConfigServicePropertySourceLocator (152) [locate] - Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/linkis-cg-engineconnmanager/linkis": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2022-02-14 15:30:48.751 [INFO ] [main                                    ] o.a.l.DataWorkCloudApplication (655) [logStartupProfileInfo] - The following profiles are active: linkis
2022-02-14 15:30:48.776 [INFO ] [main                                    ] o.a.l.DataWorkCloudApplication (87) [onApplicationEvent] - add config from config server...
2022-02-14 15:30:48.776 [INFO ] [main                                    ] o.a.l.DataWorkCloudApplication (92) [onApplicationEvent] - initialize DataWorkCloud spring application...
2022-02-14 15:30:50.278 [INFO ] [main                                    ] o.s.c.c.s.GenericScope (295) [setSerializationId] - BeanFactory id=44728779-9424-3a3f-9e78-e95f5997d504
2022-02-14 15:30:50.634 [INFO ] [main                                    ] o.e.j.u.log (169) [initialized] - Logging initialized @4628ms to org.eclipse.jetty.util.log.Slf4jLog
2022-02-14 15:30:50.830 [INFO ] [main                                    ] o.s.b.w.e.j.JettyServletWebServerFactory (147) [getWebServer] - Server initialized with port: 9102
2022-02-14 15:30:50.873 [INFO ] [main                                    ] o.e.j.s.Server (359) [doStart] - jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 1.8.0_321-b07
2022-02-14 15:30:50.905 [INFO ] [main                                    ] o.e.j.s.h.C.application (2232) [log] - Initializing Spring embedded WebApplicationContext
2022-02-14 15:30:50.905 [INFO ] [main                                    ] o.s.b.w.s.c.ServletWebServerApplicationContext (285) [prepareWebApplicationContext] - Root WebApplicationContext: initialization completed in 2128 ms
2022-02-14 15:30:51.030 [WARN ] [main                                    ] c.n.c.s.URLConfigurationSource (121) [<init>] - No URLs will be polled as dynamic configuration sources.
2022-02-14 15:30:51.031 [INFO ] [main                                    ] c.n.c.s.URLConfigurationSource (122) [<init>] - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-02-14 15:30:51.043 [INFO ] [main                                    ] c.n.c.DynamicPropertyFactory (281) [getInstance] - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@646d58cd
2022-02-14 15:30:51.104 [WARN ] [main                                    ] o.s.b.a.e.EndpointId (155) [logWarning] - Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2022-02-14 15:30:51.239 [INFO ] [main                                    ] o.e.j.s.session (333) [doStart] - DefaultSessionIdManager workerName=node0
2022-02-14 15:30:51.240 [INFO ] [main                                    ] o.e.j.s.session (338) [doStart] - No SessionScavenger set, using defaults
2022-02-14 15:30:51.241 [INFO ] [main                                    ] o.e.j.s.session (140) [startScavenging] - node0 Scavenging every 660000ms
2022-02-14 15:30:51.248 [INFO ] [main                                    ] o.e.j.s.h.ContextHandler (824) [doStart] - Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@539dd2d0{application,/,[file:///tmp/jetty-docbase.256461922550136778.9102/],AVAILABLE}
2022-02-14 15:30:51.249 [INFO ] [main                                    ] o.e.j.s.Server (399) [doStart] - Started @5246ms
2022-02-14 15:30:51.607 [INFO ] [main                                    ] o.r.Reflections (229) [scan] - Reflections took 257 ms to scan 24 urls, producing 372 keys and 4275 values 
2022-02-14 15:30:51.636 [INFO ] [main                                    ] o.a.l.r.MessageRPCReceiveRestful (41) [info] - init all receiverChoosers in spring beans, list => List(org.apache.linkis.rpc.MessageReceiverChooser@647af13d, org.apache.linkis.rpc.CommonReceiverChooser@1fa24e7)
2022-02-14 15:30:51.640 [INFO ] [main                                    ] o.a.l.r.MessageRPCReceiveRestful (41) [info] - init all receiverSenderBuilders in spring beans, list => List(org.apache.linkis.rpc.CommonReceiverSenderBuilder@15f229e8)
2022-02-14 15:30:51.648 [INFO ] [main                                    ] o.a.l.r.MessageRPCReceiveRestful (41) [info] - init RPCReceiverListenerBus with queueSize 5000 and consumeThreadSize 400.
2022-02-14 15:30:51.649 [INFO ] [main                                    ] o.a.l.r.AsynRPCMessageBus (41) [info] - RPC-Receiver-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.rpc.RPCReceiveRestful$$anon$1
2022-02-14 15:30:51.651 [INFO ] [main                                    ] o.a.l.r.MessageRPCReceiveRestful (41) [info] - init all receiverChoosers in spring beans, list => List(org.apache.linkis.rpc.MessageReceiverChooser@647af13d, org.apache.linkis.rpc.CommonReceiverChooser@4d745ac6)
2022-02-14 15:30:51.653 [INFO ] [main                                    ] o.a.l.r.MessageRPCReceiveRestful (41) [info] - init all receiverSenderBuilders in spring beans, list => List(org.apache.linkis.rpc.CommonReceiverSenderBuilder@45494046)
2022-02-14 15:30:51.858 [INFO ] [main                                    ] o.s.c.n.e.InstanceInfoFactory (72) [create] - Setting initial instance status as: STARTING
2022-02-14 15:30:51.899 [INFO ] [main                                    ] c.n.d.DiscoveryClient (365) [<init>] - Initializing Eureka in region us-east-1
2022-02-14 15:30:52.195 [INFO ] [main                                    ] c.n.d.p.DiscoveryJerseyProvider (70) [<init>] - Using JSON encoding codec LegacyJacksonJson
2022-02-14 15:30:52.195 [INFO ] [main                                    ] c.n.d.p.DiscoveryJerseyProvider (71) [<init>] - Using JSON decoding codec LegacyJacksonJson
2022-02-14 15:30:52.359 [INFO ] [main                                    ] c.n.d.p.DiscoveryJerseyProvider (80) [<init>] - Using XML encoding codec XStreamXml
2022-02-14 15:30:52.359 [INFO ] [main                                    ] c.n.d.p.DiscoveryJerseyProvider (81) [<init>] - Using XML decoding codec XStreamXml
2022-02-14 15:30:52.557 [INFO ] [main                                    ] c.n.d.s.r.a.ConfigClusterResolver (43) [getClusterEndpoints] - Resolving eureka endpoints via configuration
2022-02-14 15:30:52.573 [INFO ] [main                                    ] c.n.d.DiscoveryClient (976) [fetchRegistry] - Disable delta property : false
2022-02-14 15:30:52.574 [INFO ] [main                                    ] c.n.d.DiscoveryClient (977) [fetchRegistry] - Single vip registry refresh property : null
2022-02-14 15:30:52.574 [INFO ] [main                                    ] c.n.d.DiscoveryClient (978) [fetchRegistry] - Force full registry fetch : false
2022-02-14 15:30:52.574 [INFO ] [main                                    ] c.n.d.DiscoveryClient (979) [fetchRegistry] - Application is null : false
2022-02-14 15:30:52.574 [INFO ] [main                                    ] c.n.d.DiscoveryClient (980) [fetchRegistry] - Registered Applications size is zero : true
2022-02-14 15:30:52.575 [INFO ] [main                                    ] c.n.d.DiscoveryClient (982) [fetchRegistry] - Application version is -1: true
2022-02-14 15:30:52.575 [INFO ] [main                                    ] c.n.d.DiscoveryClient (1065) [getAndStoreFullRegistry] - Getting all instance registry info from the eureka server
2022-02-14 15:30:52.727 [INFO ] [main                                    ] c.n.d.DiscoveryClient (1074) [getAndStoreFullRegistry] - The response status is 200
2022-02-14 15:30:52.731 [INFO ] [main                                    ] c.n.d.DiscoveryClient (1288) [initScheduledTasks] - Starting heartbeat executor: renew interval is: 30
2022-02-14 15:30:52.734 [INFO ] [main                                    ] c.n.d.InstanceInfoReplicator (60) [<init>] - InstanceInfoReplicator onDemand update allowed rate per min is 4
2022-02-14 15:30:52.738 [INFO ] [main                                    ] c.n.d.DiscoveryClient (465) [<init>] - Discovery Client initialized at timestamp 1644823852737 with initial instances count: 7
2022-02-14 15:30:52.827 [INFO ] [main                                    ] o.a.l.e.c.l.ECMSyncListenerBus (41) [info] - org.apache.linkis.ecm.core.listener.ECMSyncListenerBus@738ed8d3 add a new listener => class org.apache.linkis.ecm.server.service.impl.DefaultEngineConnListService
2022-02-14 15:30:52.844 [INFO ] [main                                    ] o.a.l.e.c.l.ECMSyncListenerBus (41) [info] - org.apache.linkis.ecm.core.listener.ECMSyncListenerBus@738ed8d3 add a new listener => class org.apache.linkis.ecm.server.service.impl.DefaultECMRegisterService
2022-02-14 15:30:52.865 [INFO ] [main                                    ] o.a.l.e.c.l.ECMSyncListenerBus (41) [info] - org.apache.linkis.ecm.core.listener.ECMSyncListenerBus@738ed8d3 add a new listener => class org.apache.linkis.ecm.server.service.impl.DefaultECMHealthService
2022-02-14 15:30:52.897 [WARN ] [main                                    ] c.n.c.s.URLConfigurationSource (121) [<init>] - No URLs will be polled as dynamic configuration sources.
2022-02-14 15:30:52.898 [INFO ] [main                                    ] c.n.c.s.URLConfigurationSource (122) [<init>] - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-02-14 15:30:53.202 [INFO ] [main                                    ] o.s.s.c.ThreadPoolTaskExecutor (181) [initialize] - Initializing ExecutorService 'applicationTaskExecutor'
2022-02-14 15:30:53.397 [INFO ] [main                                    ] o.a.l.s.q.p.ParallelConsumerManager (41) [info] - The feature that auto clean up idle consumers for RpcMessageScheduler is enabled.
2022-02-14 15:30:53.402 [WARN ] [main                                    ] o.a.l.m.u.MessageUtils (44) [getBean] - can not get bean from spring ioc:org.springframework.transaction.PlatformTransactionManager
2022-02-14 15:30:53.646 [WARN ] [main                                    ] o.s.c.l.c.BlockingLoadBalancerClientAutoConfiguration$BlockingLoadBalancerClientRibbonWarnLogger (86) [logWarning] - You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
2022-02-14 15:30:53.709 [INFO ] [main                                    ] o.s.b.a.e.w.EndpointLinksResolver (58) [<init>] - Exposing 2 endpoint(s) beneath base path '/actuator'
2022-02-14 15:30:53.752 [INFO ] [main                                    ] o.s.c.n.e.s.EurekaServiceRegistry (41) [register] - Registering application LINKIS-CG-ENGINECONNMANAGER with eureka with status UP
2022-02-14 15:30:53.753 [INFO ] [main                                    ] c.n.d.DiscoveryClient (1323) [notify] - Saw local status change event StatusChangeEvent [timestamp=1644823853753, current=UP, previous=STARTING]
2022-02-14 15:30:53.756 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.DiscoveryClient (844) [register] - DiscoveryClient_LINKIS-CG-ENGINECONNMANAGER/webank:linkis-cg-engineconnmanager:9102: registering service...
2022-02-14 15:30:53.778 [INFO ] [main                                    ] o.e.j.s.h.C.application (2232) [log] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-02-14 15:30:53.778 [INFO ] [main                                    ] o.s.w.s.DispatcherServlet (525) [initServletBean] - Initializing Servlet 'dispatcherServlet'
2022-02-14 15:30:53.788 [INFO ] [main                                    ] o.s.w.s.DispatcherServlet (547) [initServletBean] - Completed initialization in 10 ms
2022-02-14 15:30:53.789 [INFO ] [main                                    ] o.e.j.s.h.C.application (2232) [log] - Initializing Spring DispatcherServlet 'springrestful'
2022-02-14 15:30:53.789 [INFO ] [main                                    ] o.s.w.s.DispatcherServlet (525) [initServletBean] - Initializing Servlet 'springrestful'
2022-02-14 15:30:53.799 [INFO ] [main                                    ] o.s.w.s.DispatcherServlet (547) [initServletBean] - Completed initialization in 9 ms
2022-02-14 15:30:53.802 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.DiscoveryClient (853) [register] - DiscoveryClient_LINKIS-CG-ENGINECONNMANAGER/webank:linkis-cg-engineconnmanager:9102 - registration status: 204
2022-02-14 15:30:53.825 [INFO ] [main                                    ] o.e.j.s.AbstractConnector (293) [doStart] - Started ServerConnector@5c1dd18{HTTP/1.1,[http/1.1]}{0.0.0.0:9102}
2022-02-14 15:30:53.827 [INFO ] [main                                    ] o.s.b.w.e.j.JettyWebServer (185) [start] - Jetty started on port(s) 9102 (http/1.1) with context path '/'
2022-02-14 15:30:53.829 [INFO ] [main                                    ] o.s.c.n.e.s.EurekaAutoServiceRegistration (145) [onApplicationEvent] - Updating port to 9102
2022-02-14 15:30:53.833 [INFO ] [main                                    ] o.a.l.r.c.RPCSpringConfiguration$$EnhancerBySpringCGLIB$$861821fe (41) [info] - DataWorkCloud RPC need register RPCReceiveRestful, now add it to configuration.
2022-02-14 15:30:53.833 [INFO ] [main                                    ] o.a.l.DataWorkCloudApplication (87) [onApplicationEvent] - add config from config server...
2022-02-14 15:30:53.833 [INFO ] [main                                    ] o.a.l.DataWorkCloudApplication (92) [onApplicationEvent] - initialize DataWorkCloud spring application...
2022-02-14 15:30:53.849 [INFO ] [main                                    ] o.a.l.DataWorkCloudApplication (61) [logStarted] - Started DataWorkCloudApplication in 6.307 seconds (JVM running for 7.845)
2022-02-14 15:30:53.856 [INFO ] [main                                    ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Deal event ECMReadyEvent([Ljava.lang.String;@ae49f31)
2022-02-14 15:30:53.869 [INFO ] [main                                    ] o.a.l.e.s.s.i.DefaultECMRegisterService (41) [info] - start register ecm
2022-02-14 15:30:54.014 [INFO ] [main                                    ] o.a.l.r.AsynRPCMessageBus (41) [info] - RPC-Sender-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.rpc.BaseRPCSender$$anon$1
2022-02-14 15:30:54.234 [INFO ] [main                                    ] c.n.c.ChainedDynamicProperty (115) [checkAndFlip] - Flipping property: linkis-cg-linkismanager.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2022-02-14 15:30:54.250 [INFO ] [main                                    ] c.n.u.c.ShutdownEnabledTimer (58) [<init>] - Shutdown hook installed for: NFLoadBalancer-PingTimer-linkis-cg-linkismanager
2022-02-14 15:30:54.250 [INFO ] [main                                    ] c.n.l.BaseLoadBalancer (197) [initWithConfig] - Client: linkis-cg-linkismanager instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=linkis-cg-linkismanager,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2022-02-14 15:30:54.280 [INFO ] [main                                    ] c.n.c.ChainedDynamicProperty (115) [checkAndFlip] - Flipping property: linkis-cg-linkismanager.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2022-02-14 15:30:54.399 [INFO ] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.s.q.p.ParallelConsumerManager (41) [info] - Start to Clean up idle consumers 
2022-02-14 15:30:54.402 [ERROR] [main                                    ] o.a.l.e.s.s.i.DefaultECMRegisterService (62) [error] - Failed to register info to linkis manager, reason: ClassNotFoundException: com.mysql.jdbc.Driver
2022-02-14 15:30:54.404 [INFO ] [Thread-24                               ] c.n.l.PollingServerListUpdater (53) [run] - Shutting down the Executor Pool for PollingServerListUpdater
2022-02-14 15:30:54.404 [INFO ] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.s.q.p.ParallelConsumerManager (41) [info] - Finished to clean up idle consumers for RpcMessageScheduler, cost 4 ms.
2022-02-14 15:30:54.409 [INFO ] [SpringContextShutdownHook               ] o.s.c.n.e.s.EurekaServiceRegistry (65) [deregister] - Unregistering application LINKIS-CG-ENGINECONNMANAGER with eureka with status DOWN
2022-02-14 15:30:54.410 [WARN ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (1321) [notify] - Saw local status change event StatusChangeEvent [timestamp=1644823854409, current=DOWN, previous=UP]
2022-02-14 15:30:54.410 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.DiscoveryClient (844) [register] - DiscoveryClient_LINKIS-CG-ENGINECONNMANAGER/webank:linkis-cg-engineconnmanager:9102: registering service...
2022-02-14 15:30:54.411 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Deal event ECMClosedEvent()
2022-02-14 15:30:54.412 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - start to kill all engines belonging the ecm
2022-02-14 15:30:54.415 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Done! success to kill all engines belonging the ecm
2022-02-14 15:30:54.416 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultECMRegisterService (41) [info] - start unRegister ecm
2022-02-14 15:30:54.418 [INFO ] [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.DiscoveryClient (853) [register] - DiscoveryClient_LINKIS-CG-ENGINECONNMANAGER/webank:linkis-cg-engineconnmanager:9102 - registration status: 204
2022-02-14 15:30:54.464 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (112) [onApplicationClosed] - wait ECM:ServiceInstance(linkis-cg-engineconnmanager, webank:9102) asyncBus empty
2022-02-14 15:30:54.466 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (118) [onApplicationClosed] - ECM asyncBus is empty
2022-02-14 15:30:54.467 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.c.l.ECMAsyncListenerBus (41) [info] - try to stop em_async_bus thread.
2022-02-14 15:30:54.468 [INFO ] [em_async_bus-Consumer-ThreadPool2       ] o.a.l.e.c.l.ECMAsyncListenerBus (41) [info] - stopped em_async_bus thread.
2022-02-14 15:30:54.468 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (120) [onApplicationClosed] - ECM is closed
2022-02-14 15:30:54.477 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.AbstractConnector (343) [doStop] - Stopped ServerConnector@5c1dd18{HTTP/1.1,[http/1.1]}{0.0.0.0:9102}
2022-02-14 15:30:54.477 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.session (158) [stopScavenging] - node0 Stopped scavenging
2022-02-14 15:30:54.479 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.h.C.application (2232) [log] - Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-02-14 15:30:54.480 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.h.C.application (2232) [log] - Destroying Spring FrameworkServlet 'springrestful'
2022-02-14 15:30:54.480 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Deal event ECMClosedEvent()
2022-02-14 15:30:54.481 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - start to kill all engines belonging the ecm
2022-02-14 15:30:54.481 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Done! success to kill all engines belonging the ecm
2022-02-14 15:30:54.481 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultECMRegisterService (41) [info] - start unRegister ecm
2022-02-14 15:30:54.501 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (112) [onApplicationClosed] - wait ECM:ServiceInstance(linkis-cg-engineconnmanager, webank:9102) asyncBus empty
2022-02-14 15:30:54.502 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (118) [onApplicationClosed] - ECM asyncBus is empty
2022-02-14 15:30:54.502 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (120) [onApplicationClosed] - ECM is closed
2022-02-14 15:30:54.504 [INFO ] [SpringContextShutdownHook               ] o.e.j.s.h.ContextHandler (1007) [doStop] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@539dd2d0{application,/,[file:///tmp/jetty-docbase.256461922550136778.9102/],UNAVAILABLE}
2022-02-14 15:30:54.520 [INFO ] [SpringContextShutdownHook               ] o.s.s.c.ThreadPoolTaskExecutor (218) [shutdown] - Shutting down ExecutorService 'applicationTaskExecutor'
2022-02-14 15:30:54.525 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Deal event ECMClosedEvent()
2022-02-14 15:30:54.525 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - start to kill all engines belonging the ecm
2022-02-14 15:30:54.525 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultEngineConnListService (41) [info] - Done! success to kill all engines belonging the ecm
2022-02-14 15:30:54.525 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.s.i.DefaultECMRegisterService (41) [info] - start unRegister ecm
2022-02-14 15:30:54.529 [WARN ] [SpringContextShutdownHook               ] c.n.c.s.URLConfigurationSource (121) [<init>] - No URLs will be polled as dynamic configuration sources.
2022-02-14 15:30:54.529 [INFO ] [SpringContextShutdownHook               ] c.n.c.s.URLConfigurationSource (122) [<init>] - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2022-02-14 15:30:54.530 [INFO ] [SpringContextShutdownHook               ] c.n.c.DynamicPropertyFactory (281) [getInstance] - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@5a3ba832
2022-02-14 15:30:54.557 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (112) [onApplicationClosed] - wait ECM:ServiceInstance(linkis-cg-engineconnmanager, webank:9102) asyncBus empty
2022-02-14 15:30:54.557 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (118) [onApplicationClosed] - ECM asyncBus is empty
2022-02-14 15:30:54.558 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.s.ECMApplicationListener$$EnhancerBySpringCGLIB$$be90aa3a (120) [onApplicationClosed] - ECM is closed
2022-02-14 15:30:54.561 [INFO ] [SpringContextShutdownHook               ] c.n.u.c.ShutdownEnabledTimer (67) [cancel] - Shutdown hook removed for: NFLoadBalancer-PingTimer-linkis-cg-linkismanager
2022-02-14 15:30:54.561 [INFO ] [SpringContextShutdownHook               ] c.n.u.c.ShutdownEnabledTimer (72) [cancel] - Exception caught (might be ok if at shutdown) java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[?:1.8.0_321]
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[?:1.8.0_321]
	at com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:70) [netflix-commons-util-0.1.1.jar:?]
	at com.netflix.loadbalancer.BaseLoadBalancer.cancelPingTask(BaseLoadBalancer.java:632) [ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.BaseLoadBalancer.shutdown(BaseLoadBalancer.java:883) [ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer.shutdown(DynamicServerListLoadBalancer.java:285) [ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:280) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:214) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:92) [spring-cloud-context-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) [spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]

2022-02-14 15:30:54.578 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (906) [shutdown] - Shutting down DiscoveryClient ...
2022-02-14 15:30:57.580 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (940) [unregister] - Unregistering ...
2022-02-14 15:30:57.588 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (942) [unregister] - DiscoveryClient_LINKIS-CG-ENGINECONNMANAGER/webank:linkis-cg-engineconnmanager:9102 - deregister  status: 200
2022-02-14 15:30:57.599 [INFO ] [SpringContextShutdownHook               ] c.n.d.DiscoveryClient (929) [shutdown] - Completed shut down of DiscoveryClient

**Comment by casionone** [comment]
Should resolve this exception
  `Failed to register info to linkis manager, reason: ClassNotFoundException: com.mysql.jdbc.Driver.`
Solution: https://linkis.apache.org/zh-CN/docs/1.0.3/development/linkis_compile_and_package#12-%E4%BF%AE%E6%94%B9%E4%BE%9D%E8%B5%96%E9%85%8D%E7%BD%AE

**Comment by breeze1126** [comment]
重新把对应的mysql-connector-java.jar 包放到对应的服务lib下面 重启linkis成功了。
多谢释疑。
