### ISSUE TITLE
[Bug] An error is reported when the job flow is executed

### ISSUE THREAD

**Issue by Andywli** [apache/incubator-linkis#1629]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

Scripts执行python脚本(脚本内容是很简单的print)正常执行成功，通过任务调度系统也可以执行成功，通过作业流的编辑作业脚本页面也可执行成功，但是通过作业流执行时报错

Scripts executes the python script (the script content is very simple print) and successfully executes normally. It can also be executed successfully through the task scheduling system. It can also be executed successfully through the editing job script page of the job stream, but an error is reported when executed through the job stream.

Error Info：

> 
> You can go to this path(/opt/kepler/work/engine/hadoop/workDir/9c28976e-63ba-4d9d-b85e-b37d84144596/logs) to find the reason or ask the administrator for help ,ip: host1 ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: host1 ,port: 9104 ,serviceKind: linkis-cg-entrance
> Exception in thread "main" java.lang.NullPointerException
>     at com.webank.wedatasphere.linkis.rpc.sender.SpringCloudFeignConfigurationCache$.getClient(SpringCloudFeignConfigurationCache.scala:73)
>     at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender.doBuilder(SpringMVCRPCSender.scala:49)
> 
> 
> 
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
> Exception in thread "main" java.lang.NullPointerException
> 	at com.webank.wedatasphere.linkis.rpc.sender.SpringCloudFeignConfigurationCache$.getClient(SpringCloudFeignConfigurationCache.scala:73)
> 	at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender.doBuilder(SpringMVCRPCSender.scala:49)
> 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.newRPC(BaseRPCSender.scala:67)
> 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.com$webank$wedatasphere$linkis$rpc$BaseRPCSender$$getRPC(BaseRPCSender.scala:54)
> 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.send(BaseRPCSender.scala:105)
> 	at com.webank.wedatasphere.linkis.engineconn.callback.service.AbstractEngineConnStartUpCallback.callback(EngineConnCallback.scala:39)
> 	at com.webank.wedatasphere.linkis.engineconn.callback.hook.CallbackEngineConnHook.afterEngineServerStartFailed(CallbackEngineConnHook.scala:63)
> 	at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer$$anonfun$main$15.apply(EngineConnServer.scala:64)
> 	at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer$$anonfun$main$15.apply(EngineConnServer.scala:64)
> 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> 	at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:64)
> 	at com.webank.wedatasphere.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala)
> 
![image](https://user-images.githubusercontent.com/55732213/157189313-11fd5702-af6b-4007-9995-e02b39cb862f.png)
![image1](https://user-images.githubusercontent.com/55732213/157189330-908cb3cb-a8bd-44e4-b5c0-aa9d57a84436.png)

### Relevent platform

·

### Reproduction script

·

### Anything else

This question comes from the QA documentation of the Linkis community
QA Link：https://docs.qq.com/doc/DSGZhdnpMV3lTUUxq

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Andywli** [comment]
解决方案：/opt/kepler/work/engine/hadoop/workDir/9c28976e-63ba-4d9d-b85e-b37d84144596目录下conf为空导致的。lib和conf是在微服务启动时，由系统检查到（linkis/lib/linkis-engineconn-plugins/python）python引擎物料包zip变化，自动上传至engine/engineConnPublickDir/目录下。临时解决问题是将linkis/lib/linkis-engineconn-plugins/python下的lib和conf内容复制到engine/engineConnPublickDir/对应的目录（即workDir/9c28976e-63ba-4d9d-b85e-b37d84144596里的外链接引用的目录）下。正式方案需解决物料包变化未能成功上传到engineConnPublickDir的问题。

**Comment by Andywli** [comment]
Solution: **The conf in the /opt/kepler/work/engine/hadoop/workDir/9c28976e-63ba-4d9d-b85e-b37d84144596** directory is empty. lib and conf are checked by the system when the microservice starts **(linkis/lib/linkis-engineconn-plugins/python)** python engine material package zip changes, and automatically uploaded to the engine/engineConnPublickDir/ directory. 

The temporary solution to the problem is to copy the lib and conf content under **linkis/lib/linkis-engineconn-plugins/python** to the corresponding directory of engine/engineConnPublickDir/ (that is, workDir/9c28976e-63ba-4d9d-b85e-b37d84144596 in the external link referenced Under contents. The official solution needs to solve the problem that the material package changes cannot be successfully uploaded to engineConnPublickDir.
