### ISSUE TITLE
The Spark engine fails to start when using spark3.2

### ISSUE THREAD

**Issue by lordk911** [apache/incubator-linkis#1802]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

I complie linkis1.0.3 with spark3.2.1 , but the engine fails to start (I can use spark-shell on yarn ): 

```
2022-03-25 21:02:11.275 INFO  [main] org.apache.linkis.engineconn.acessible.executor.log.SendAppender 64 <init> - SendAppender init success

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.2.RELEASE)

2022-03-25 21:02:11.470 INFO  [main] org.apache.linkis.DataWorkCloudApplication 655 logStartupProfileInfo - The following profiles are active: engineconn
2022-03-25 21:02:11.524 INFO  [main] org.apache.linkis.DataWorkCloudApplication 88 onApplicationEvent - add config from config server...
2022-03-25 21:02:11.524 INFO  [main] org.apache.linkis.DataWorkCloudApplication 93 onApplicationEvent - initialize DataWorkCloud spring application...
2022-03-25 21:02:14.111 WARN  [main] com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
2022-03-25 21:02:14.113 INFO  [main] com.netflix.config.sources.URLConfigurationSource 122 <init> - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or mak
e config.properties available on classpath.
2022-03-25 21:02:14.129 INFO  [main] com.netflix.config.DynamicPropertyFactory 281 getInstance - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@332fc35
c
2022-03-25 21:02:15.054 INFO  [main] org.apache.linkis.engineconn.executor.listener.EngineConnAsyncListenerBus 41 info - EngineConn-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.engineconn.acessible
.executor.service.DefaultExecutorHeartbeatService
2022-03-25 21:02:15.060 INFO  [main] org.apache.linkis.engineconn.executor.listener.EngineConnAsyncListenerBus 41 info - EngineConn-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.engineconn.acessible
.executor.service.DefaultAccessibleService
2022-03-25 21:02:15.101 INFO  [main] org.apache.linkis.engineconn.executor.listener.EngineConnAsyncListenerBus 41 info - EngineConn-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.engineconn.acessible
.executor.service.EngineConnTimedLockService
2022-03-25 21:02:15.111 INFO  [main] org.apache.linkis.engineconn.executor.listener.EngineConnSyncListenerBus 41 info - org.apache.linkis.engineconn.executor.listener.EngineConnSyncListenerBus@136d1d58 add a new listener =
> class org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl
2022-03-25 21:02:15.125 INFO  [main] org.apache.linkis.engineplugin.spark.extension.SparkPreExecutionHook$ 41 info - Get a preExecutionHook of CSSparkPreExecutionHook register
2022-03-25 21:02:15.132 INFO  [main] org.apache.linkis.engineplugin.spark.extension.SparkPostExecutionHook$ 41 info - Get a postExecutionHook of MDQPostHook register
2022-03-25 21:02:15.137 INFO  [main] org.apache.linkis.engineplugin.spark.extension.SparkPreExecutionHook$ 41 info - Get a preExecutionHook of MDQPreHook register
2022-03-25 21:02:15.313 INFO  [main] org.apache.linkis.rpc.MessageRPCReceiveRestful 41 info - init all receiverChoosers in spring beans, list => List(org.apache.linkis.rpc.MessageReceiverChooser@c9518ee, org.apache.linkis.
rpc.CommonReceiverChooser@1398e3aa)
2022-03-25 21:02:15.316 INFO  [main] org.apache.linkis.rpc.MessageRPCReceiveRestful 41 info - init all receiverSenderBuilders in spring beans, list => List(org.apache.linkis.rpc.CommonReceiverSenderBuilder@320bfc61)
2022-03-25 21:02:15.320 INFO  [main] org.apache.linkis.rpc.MessageRPCReceiveRestful 41 info - init RPCReceiverListenerBus with queueSize 5000 and consumeThreadSize 400.
2022-03-25 21:02:15.322 INFO  [main] org.apache.linkis.rpc.AsynRPCMessageBus 41 info - RPC-Receiver-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.rpc.RPCReceiveRestful$$anon$1
2022-03-25 21:02:15.325 INFO  [main] org.apache.linkis.rpc.MessageRPCReceiveRestful 41 info - init all receiverChoosers in spring beans, list => List(org.apache.linkis.rpc.MessageReceiverChooser@c9518ee, org.apache.linkis.
rpc.CommonReceiverChooser@3af1b643)
2022-03-25 21:02:15.327 INFO  [main] org.apache.linkis.rpc.MessageRPCReceiveRestful 41 info - init all receiverSenderBuilders in spring beans, list => List(org.apache.linkis.rpc.CommonReceiverSenderBuilder@189f5ed8)
2022-03-25 21:02:15.391 WARN  [main] com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
2022-03-25 21:02:15.392 INFO  [main] com.netflix.config.sources.URLConfigurationSource 122 <init> - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or mak
e config.properties available on classpath.
2022-03-25 21:02:15.907 WARN  [main] org.apache.linkis.message.utils.MessageUtils 44 getBean - can not get bean from spring ioc:org.apache.linkis.engineconn.acessible.executor.service.EngineConnConcurrentLockService
2022-03-25 21:02:15.921 INFO  [main] org.apache.linkis.scheduler.queue.parallelqueue.ParallelConsumerManager 41 info - The feature that auto clean up idle consumers for RpcMessageScheduler is enabled.
2022-03-25 21:02:15.927 WARN  [main] org.apache.linkis.message.utils.MessageUtils 44 getBean - can not get bean from spring ioc:org.springframework.transaction.PlatformTransactionManager
2022-03-25 21:02:16.511 INFO  [main] org.apache.linkis.rpc.conf.RPCSpringConfiguration$$EnhancerBySpringCGLIB$$c0eea499 41 info - DataWorkCloud RPC need register RPCReceiveRestful, now add it to configuration.
2022-03-25 21:02:16.512 INFO  [main] org.apache.linkis.DataWorkCloudApplication 88 onApplicationEvent - add config from config server...
2022-03-25 21:02:16.512 INFO  [main] org.apache.linkis.DataWorkCloudApplication 93 onApplicationEvent - initialize DataWorkCloud spring application...
2022-03-25 21:02:16.531 INFO  [main] org.apache.linkis.DataWorkCloudApplication 61 logStarted - Started DataWorkCloudApplication in 6.323 seconds (JVM running for 9.352)
2022-03-25 21:02:16.704 INFO  [main] org.apache.linkis.rpc.AsynRPCMessageBus 41 info - RPC-Sender-Asyn-Thread-ListenerBus add a new listener => class org.apache.linkis.rpc.BaseRPCSender$$anon$1
2022-03-25 21:02:16.923 INFO  [Linkis-Default-Scheduler-Thread-1] org.apache.linkis.scheduler.queue.parallelqueue.ParallelConsumerManager 41 info - Start to Clean up idle consumers 
2022-03-25 21:02:16.930 INFO  [Linkis-Default-Scheduler-Thread-1] org.apache.linkis.scheduler.queue.parallelqueue.ParallelConsumerManager 41 info - Finished to clean up idle consumers for RpcMessageScheduler, cost 7 ms.
2022-03-25 21:02:17.222 INFO  [main] com.netflix.config.ChainedDynamicProperty 115 checkAndFlip - Flipping property: linkis-cg-engineconnmanager.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availab
ilityFilteringRule.activeConnectionsLimit = 2147483647
2022-03-25 21:02:17.248 INFO  [main] com.netflix.util.concurrent.ShutdownEnabledTimer 58 <init> - Shutdown hook installed for: NFLoadBalancer-PingTimer-linkis-cg-engineconnmanager
2022-03-25 21:02:17.249 INFO  [main] com.netflix.loadbalancer.BaseLoadBalancer 197 initWithConfig - Client: linkis-cg-engineconnmanager instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=linkis
-cg-engineconnmanager,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2022-03-25 21:02:17.257 INFO  [main] com.netflix.loadbalancer.DynamicServerListLoadBalancer 222 enableAndInitLearnNewServersFeature - Using serverListUpdater PollingServerListUpdater
2022-03-25 21:02:17.281 INFO  [main] com.netflix.config.ChainedDynamicProperty 115 checkAndFlip - Flipping property: linkis-cg-engineconnmanager.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availab
ilityFilteringRule.activeConnectionsLimit = 2147483647
2022-03-25 21:02:17.287 INFO  [main] com.netflix.loadbalancer.DynamicServerListLoadBalancer 150 restOfInit - DynamicServerListLoadBalancer for client linkis-cg-engineconnmanager initialized: DynamicServerListLoadBalancer:{
NFLoadBalancer:name=linkis-cg-engineconnmanager,current list of Servers=[host-10-0-105-243:9102],Load balancer stats=Zone stats: {defaultzone=[Zone:defaultzone;        Instance count:1;       Active connections count: 0; Circuit breaker tripped count: 0;        Active connections per server: 0.0;]
},Server stats: [[Server:host-10-0-105-243:9102;        Zone:defaultZone;       Total Requests:0;       Successive connection failure:0;        Total blackout seconds:0;       Last connection made:Thu Jan 01 08:00:00 CST 1
970;    First connection made: Thu Jan 01 08:00:00 CST 1970;    Active Connections:0;   total failure count in last (1000) msecs:0;     average resp time:0.0;  90 percentile resp time:0.0;    95 percentile resp time:0.0; -min resp time:0.0;      max resp time:0.0;      stddev resp time:0.0]
]}ServerList:org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList@6fec6b75
2022-03-25 21:02:17.374 INFO  [main] org.apache.linkis.engineconn.computation.executor.hook.ComputationEngineConnHook 41 info - <--------------------SpringBoot App init succeed-------------------->
2022-03-25 21:02:17.374 INFO  [main] org.apache.linkis.engineconn.launch.EngineConnServer$ 41 info - Finished to execute hook of beforeCreateEngineConn.
2022-03-25 21:02:17.394 INFO  [main] org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory 41 info - ------ Create new SparkContext {yarn} -------
2022-03-25 21:02:17.400 INFO  [main] org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory 41 info - outputDir====> /data/dss-dir/appcom/bigtop/workDir/c5def50b-94b0-4a32-b904-474283950c63/tmp/repl-efe9dcfb-d
21a-405e-891a-7646d27b890d
2022-03-25 21:02:17.401 INFO  [main] org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory 41 info - print current thread name org.apache.spark.util.MutableURLClassLoader@38a1c423
2022-03-25 21:02:17.402 INFO  [main] org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory 41 info - ------ Create new SparkContext {yarn} -------
2022-03-25 21:02:17.451 INFO  [main] org.apache.hadoop.hive.conf.HiveConf 187 findConfigFile - Found configuration file file:/data/soft/spark-3.2.1-bin-hadoop3.2/conf/hive-site.xml
2022-03-25 21:02:17.704 INFO  [main] org.apache.spark.SparkContext 57 logInfo - Running Spark version 3.2.1
2022-03-25 21:02:17.880 INFO  [main] org.apache.spark.resource.ResourceUtils 57 logInfo - ==============================================================
2022-03-25 21:02:17.880 INFO  [main] org.apache.spark.resource.ResourceUtils 57 logInfo - No custom resources configured for spark.driver.
2022-03-25 21:02:17.881 INFO  [main] org.apache.spark.resource.ResourceUtils 57 logInfo - ==============================================================
2022-03-25 21:02:17.882 INFO  [main] org.apache.spark.SparkContext 57 logInfo - Submitted application: Linkis-EngineConn-Spark_IDE
2022-03-25 21:02:17.923 INFO  [main] org.apache.spark.resource.ResourceProfile 57 logInfo - Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memo
ry, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
2022-03-25 21:02:17.931 INFO  [main] org.apache.spark.resource.ResourceProfile 57 logInfo - Limiting resource is cpus at 1 tasks per executor
2022-03-25 21:02:17.934 INFO  [main] org.apache.spark.resource.ResourceProfileManager 57 logInfo - Added ResourceProfile id: 0
2022-03-25 21:02:18.020 INFO  [main] org.apache.spark.SecurityManager 57 logInfo - Changing view acls to: bigtop
2022-03-25 21:02:18.020 INFO  [main] org.apache.spark.SecurityManager 57 logInfo - Changing modify acls to: bigtop
2022-03-25 21:02:18.021 INFO  [main] org.apache.spark.SecurityManager 57 logInfo - Changing view acls groups to: 
2022-03-25 21:02:18.022 INFO  [main] org.apache.spark.SecurityManager 57 logInfo - Changing modify acls groups to: 
2022-03-25 21:02:18.022 INFO  [main] org.apache.spark.SecurityManager 57 logInfo - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(bigtop); groups with view permissions: Set();
 users  with modify permissions: Set(bigtop); groups with modify permissions: Set()
2022-03-25 21:02:18.262 INFO  [PollingServerListUpdater-0] com.netflix.config.ChainedDynamicProperty 115 checkAndFlip - Flipping property: linkis-cg-engineconnmanager.ribbon.ActiveConnectionsLimit to use NEXT property: niw
s.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2022-03-25 21:02:18.490 INFO  [main] org.apache.spark.util.Utils 57 logInfo - Successfully started service 'sparkDriver' on port 45020.
2022-03-25 21:02:18.545 INFO  [main] org.apache.spark.SparkEnv 57 logInfo - Registering MapOutputTracker
2022-03-25 21:02:18.728 INFO  [main] org.apache.spark.SparkEnv 57 logInfo - Registering BlockManagerMaster
2022-03-25 21:02:18.786 INFO  [main] org.apache.spark.storage.BlockManagerMasterEndpoint 57 logInfo - Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
2022-03-25 21:02:18.787 INFO  [main] org.apache.spark.storage.BlockManagerMasterEndpoint 57 logInfo - BlockManagerMasterEndpoint up
2022-03-25 21:02:18.829 INFO  [main] org.apache.spark.SparkEnv 57 logInfo - Registering BlockManagerMasterHeartbeat
2022-03-25 21:02:18.864 INFO  [main] org.apache.spark.storage.DiskBlockManager 57 logInfo - Created local directory at /data/dss-dir/appcom/bigtop/workDir/c5def50b-94b0-4a32-b904-474283950c63/tmp/blockmgr-5cd93382-6ca4-49a
6-a126-f8c8f9d26465
2022-03-25 21:02:18.893 INFO  [main] org.apache.spark.storage.memory.MemoryStore 57 logInfo - MemoryStore started with capacity 434.4 MiB
2022-03-25 21:02:18.939 INFO  [main] org.apache.spark.SparkEnv 57 logInfo - Registering OutputCommitCoordinator
2022-03-25 21:02:19.076 INFO  [main] org.sparkproject.jetty.util.log 170 initialized - Logging initialized @11897ms to org.sparkproject.jetty.util.log.Slf4jLog
2022-03-25 21:02:19.186 INFO  [main] org.sparkproject.jetty.server.Server 375 doStart - jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 1.8.0_281-b09
2022-03-25 21:02:19.216 INFO  [main] org.sparkproject.jetty.server.Server 415 doStart - Started @12038ms
2022-03-25 21:02:19.281 INFO  [main] org.sparkproject.jetty.server.AbstractConnector 331 doStart - Started ServerConnector@1c24a99e{HTTP/1.1, (http/1.1)}{0.0.0.0:4040}
2022-03-25 21:02:19.282 INFO  [main] org.apache.spark.util.Utils 57 logInfo - Successfully started service 'SparkUI' on port 4040.
2022-03-25 21:02:19.316 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@22801099{/jobs,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.322 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@4358797d{/jobs/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.324 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@724f5157{/jobs/job,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.326 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@402ceac2{/jobs/job/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.328 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@580930b7{/stages,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.330 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@39086d6b{/stages/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.331 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@2122eb64{/stages/stage,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.333 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@23d5c418{/stages/stage/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.335 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@68e1f0a1{/stages/pool,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.337 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@11a0aee8{/stages/pool/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.338 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@6c76a792{/storage,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.340 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@26501a93{/storage/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.341 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@5dc1c1c1{/storage/rdd,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.343 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@50f572e8{/storage/rdd/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.344 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@12cd1fe6{/environment,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.346 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@241f3244{/environment/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.348 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@17c158ca{/executors,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.349 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@26309e6f{/executors/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.351 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@1cc1813a{/executors/threadDump,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.354 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@45c99f3d{/executors/threadDump/json,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.370 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@86126ad{/static,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.372 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@514abad9{/,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.374 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@3c2ed946{/api,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.375 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@15a7fda8{/jobs/job/kill,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.377 INFO  [main] org.sparkproject.jetty.server.handler.ContextHandler 915 doStart - Started o.s.j.s.ServletContextHandler@36fe4eb0{/stages/stage/kill,null,AVAILABLE,@Spark}
2022-03-25 21:02:19.380 INFO  [main] org.apache.spark.ui.SparkUI 57 logInfo - Bound SparkUI to 0.0.0.0, and started at http://host-10-0-105-243:4040
2022-03-25 21:02:19.395 INFO  [main] org.apache.spark.SparkContext 57 logInfo - Added JAR file:/data/dss-dir/appcom/engineConnPublickDir/31044f31-1503-4742-902b-257eed1b8caa/v000003/lib/linkis-engineplugin-spark-1.0.3.jar 
at spark://host-10-0-105-243:45020/jars/linkis-engineplugin-spark-1.0.3.jar with timestamp 1648213337695
2022-03-25 21:02:19.535 WARN  [main] org.apache.spark.scheduler.FairSchedulableBuilder 69 logWarning - Fair Scheduler configuration file not found so jobs will be scheduled in FIFO order. To use fair scheduling, configure 
pools in fairscheduler.xml or set spark.scheduler.allocation.file to a file that contains the configuration.
2022-03-25 21:02:19.539 INFO  [main] org.apache.spark.scheduler.FairSchedulableBuilder 57 logInfo - Created default pool: default, schedulingMode: FIFO, minShare: 0, weight: 1
2022-03-25 21:02:19.597 WARN  [main] org.apache.spark.util.Utils 69 logWarning - spark.executor.instances less than spark.dynamicAllocation.minExecutors is invalid, ignoring its setting, please update your configs.
2022-03-25 21:02:19.599 INFO  [main] org.apache.spark.util.Utils 57 logInfo - Using initial executors = 3, max of spark.dynamicAllocation.initialExecutors, spark.dynamicAllocation.minExecutors and spark.executor.instances
2022-03-25 21:02:20.078 INFO  [main] org.apache.spark.deploy.yarn.Client 57 logInfo - Requesting a new application from cluster with 3 NodeManagers
2022-03-25 21:02:20.793 INFO  [main] org.apache.hadoop.conf.Configuration 2827 getConfResourceAsInputStream - found resource resource-types.xml at file:/etc/hadoop/3.1.4.0-315/0/resource-types.xml
2022-03-25 21:02:20.814 INFO  [main] org.apache.spark.deploy.yarn.Client 57 logInfo - Verifying our application has not requested more than the maximum memory capability of the cluster (24064 MB per container)
2022-03-25 21:02:20.815 INFO  [main] org.apache.spark.deploy.yarn.Client 57 logInfo - Will allocate AM container, with 896 MB memory including 384 MB overhead
2022-03-25 21:02:20.815 INFO  [main] org.apache.spark.deploy.yarn.Client 57 logInfo - Setting up container launch context for our AM
2022-03-25 21:02:20.819 INFO  [main] org.apache.spark.deploy.yarn.Client 57 logInfo - Setting up the launch environment for our AM container
2022-03-25 21:02:20.826 INFO  [main] org.apache.spark.deploy.yarn.Client 57 logInfo - Preparing resources for our AM container
2022-03-25 21:02:20.854 ERROR [main] org.apache.spark.SparkContext 94 logError - Error initializing SparkContext. java.lang.IllegalStateException: null
        at org.apache.hadoop.thirdparty.com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[hadoop-client-runtime-3.3.1.jar:1.1.1]
        at org.apache.hadoop.ipc.Client.setCallIdAndRetryCount(Client.java:119) ~[hadoop-client-api-3.3.1.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:162) ~[hadoop-client-api-3.3.1.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-client-api-3.3.1.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-client-api-3.3.1.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-client-api-3.3.1.jar:?]
        at com.sun.proxy.$Proxy189.delete(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.delete(DFSClient.java:1601) ~[hadoop-hdfs-client-3.1.1.3.1.4.0-315.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:947) ~[hadoop-hdfs-client-3.1.1.3.1.4.0-315.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:944) ~[hadoop-hdfs-client-3.1.1.3.1.4.0-315.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-client-api-3.3.1.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:954) ~[hadoop-hdfs-client-3.1.1.3.1.4.0-315.jar:?]
        at org.apache.spark.deploy.yarn.Client.cleanupStagingDirInternal$1(Client.scala:232) ~[spark-yarn_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.yarn.Client.cleanupStagingDir(Client.scala:241) ~[spark-yarn_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:215) ~[spark-yarn_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62) ~[spark-yarn_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:220) ~[spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:581) ~[spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690) ~[spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949) ~[spark-sql_2.12-3.2.1.jar:3.2.1]
        at scala.Option.getOrElse(Option.scala:189) [scala-library-2.12.15.jar:?]
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943) [spark-sql_2.12-3.2.1.jar:3.2.1]
        at org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory.createSparkSession(SparkEngineConnFactory.scala:119) [linkis-engineplugin-spark-1.0.3.jar:1.0.3]
        at org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory.createEngineConnSession(SparkEngineConnFactory.scala:77) [linkis-engineplugin-spark-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory.createEngineConn(EngineConnFactory.scala:48) [linkis-engineconn-plugin-core-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory.createEngineConn$(EngineConnFactory.scala:46) [linkis-engineconn-plugin-core-1.0.3.jar:1.0.3]
        at org.apache.linkis.engineplugin.spark.factory.SparkEngineConnFactory.createEngineConn(SparkEngineConnFactory.scala:42) [linkis-engineplugin-spark-1.0.3.jar:1.0.3]
        at org.apache.linkis.engineconn.core.engineconn.DefaultEngineConnManager.createEngineConn(EngineConnManager.scala:45) [linkis-engineconn-core-1.0.3.jar:1.0.3]
        at org.apache.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:65) [linkis-engineconn-launch-1.0.3.jar:1.0.3]
        at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala) [linkis-engineconn-launch-1.0.3.jar:1.0.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052) [spark-core_2.12-3.2.1.jar:3.2.1]
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) [spark-core_2.12-3.2.1.jar:3.2.1]

2022-03-25 21:02:20.882 INFO  [main] org.sparkproject.jetty.server.AbstractConnector 381 doStop - Stopped Spark@1c24a99e{HTTP/1.1, (http/1.1)}{0.0.0.0:4040}
2022-03-25 21:02:20.884 INFO  [main] org.apache.spark.ui.SparkUI 57 logInfo - Stopped Spark web UI at http://host-10-0-105-243:4040
```
I need some clue to find out the reason.

### Relevent platform

DSS 1.0.1 \ Linkis 1.0.3 \ Spark 3.2.1 \ Hadoop3

### Reproduction script

 nothing

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by yyh2954360585** [comment]
Hello, have you finished this question
