### ISSUE TITLE
[Bug] [1.0.2] Linkis-computation-client failed to submit jobs

### ISSUE THREAD

**Issue by mindflow94** [apache/incubator-linkis#1911]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

在我的项目里，引入了`linkis-computation-client`依赖，通过构造`SubmittableInteractiveJob`来提交作业，在运行中遇到以下两个报错：
`Exception in thread "main" java.lang.StackOverflowError
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:39)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
`

在获取作业信息时候，出现以下报错：
`java.lang.NullPointerException: null
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$$anonfun$getJobInfoResult$1.apply(StorableLinkisJob.scala:50)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$$anonfun$getJobInfoResult$1.apply(StorableLinkisJob.scala:50)
	at com.webank.wedatasphere.linkis.common.utils.Logging$class.info(Logging.scala:40)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.info(StorableLinkisJob.scala:74)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.getJobInfoResult(StorableLinkisJob.scala:50)
	at com.webank.wedatasphere.linkis.computation.client.interactive.SubmittableInteractiveJob.com$webank$wedatasphere$linkis$computation$client$interactive$InteractiveJob$$super$getJobInfoResult(InteractiveJob.scala:69)
	at com.webank.wedatasphere.linkis.computation.client.interactive.InteractiveJob$class.getJobInfoResult(InteractiveJob.scala:65)
	at com.webank.wedatasphere.linkis.computation.client.interactive.SubmittableInteractiveJob.getJobInfoResult(InteractiveJob.scala:69)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableLinkisJob$class.isCompleted(StorableLinkisJob.scala:69)
	at com.webank.wedatasphere.linkis.computation.client.job.StorableSubmittableLinkisJob.isCompleted(StorableLinkisJob.scala:74)`

### Relevent platform

1.0.2

### Reproduction script

`String gatewayUrl = "";
        String code = "ls /" ;
        String runType = "shell";
        String user = "hadoop";
        LinkisJobClient.config().setDefaultServerUrl(gatewayUrl);
        InteractiveJobBuilder builder = LinkisJobClient.interactive().builder();
        builder.setCode(code);
        builder.setRunTypeStr(runType);
        builder.addExecuteUser(user);
        builder.addLabel(LabelKeyUtils.ENGINE_TYPE_LABEL_KEY(), "shell-1");
        builder.addLabel(LabelKeyUtils.USER_CREATOR_LABEL_KEY(), "hadoop-IDE");
        SubmittableInteractiveJob job = builder.build();
        job.submit();
        job.waitForCompleted();`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
Thank you, please try the latest version after 1.0.3

**Comment by mindflow94** [comment]
> Thank you, please try the latest version after 1.0.3

通过引入1.0.3版本的`linkis-computation-client`，使用相同的代码提交，也会出现相同的错误。两个版本的代码看起来也是一样的。

`Exception in thread "main" java.lang.StackOverflowError
	at org.apache.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:39)
	at org.apache.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at org.apache.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at org.apache.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at org.apache.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at org.apache.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at org.apache.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at org.apache.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)
	at org.apache.linkis.computation.client.job.StorableLinkisJob$class.wrapperObj(StorableLinkisJob.scala:38)
	at org.apache.linkis.computation.client.job.StorableSubmittableLinkisJob.wrapperId(StorableLinkisJob.scala:84)`
