### ISSUE TITLE
[Bug] Failed  to async(iZbp14j2amyqhhwlqedv5kZ:9101_63) createEngine, can Retry true org.apache.linkis.common.exception.LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3} not found ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager The request of update node metrics was ignored, because the node xxxxx:9102 is not exist.

### ISSUE THREAD

**Issue by gongzh021** [apache/incubator-linkis#1928]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-manager

### What happened + What you expected to happen

各位大佬，我在前端执行SQL查询时报错如下：

2022-04-08 16:59:47.260 [INFO ] [AskEngineService-Thread-127             ] o.a.l.m.a.s.e.DefaultEngineCreateService (41) [info] - Start to create Engine for request: EngineCreateRequest{labels={userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3}, timeOut=660000, user='root', createService='dssmark_id: mark_2', description='null'}.
2022-04-08 16:59:47.269 [INFO ] [AskEngineService-Thread-128             ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (123) [apply] - Failed  to async(iZbp14j2amyqhhwlqedv5kZ:9101_63) createEngine, can Retry true org.apache.linkis.common.exception.LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=sql, engineType=spark-2.4.3} not found ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager
        at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.scala:177) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:94) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:84) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

2022-04-08 16:59:49.168 [INFO ] [Linkis-Default-Scheduler-Thread-16      ] o.a.l.m.a.s.m.NodeHeartbeatMonitor (41) [info] - Start to check the health of the node
2022-04-08 16:59:49.173 [INFO ] [Linkis-Default-Scheduler-Thread-16      ] o.a.l.m.a.s.m.NodeHeartbeatMonitor (41) [info] - Finished to check the health of the node
2022-04-08 17:00:02.444 [INFO ] [RpcMessageScheduler-ThreadPool-2453     ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}

2022-04-08 17:40:24.195 [INFO ] [RpcMessageScheduler-ThreadPool-2539     ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 17:40:24.200 [WARN ] [RpcMessageScheduler-ThreadPool-2539     ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
2022-04-08 17:40:54.193 [INFO ] [RpcMessageScheduler-ThreadPool-2540     ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 17:40:54.197 [WARN ] [RpcMessageScheduler-ThreadPool-2540     ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.

### Relevent platform

null

### Reproduction script

null

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
Check whether the table `linkis_cg_manager_service_instance` has data
you can try to truncating this table then restart linkis-cg-engineconnmanager service

**Comment by gongzh021** [comment]
> Check whether the table `linkis_cg_manager_service_instance` has data you can try to truncating this table then restart linkis-cg-engineconnmanager service

感谢大佬的回复，linkis_cg_manager_service_instance 表中没有数据，truncating表后，重启linkis-cg-engineconnmanager 服务问题依然存在！

**Comment by chenPlane** [comment]
> 

How did you finally solve this problem?

**Comment by peacewong** [comment]
You can check whether the information of the EngineConnManager service registered in eureka is consistent with the error information. If they are inconsistent, you need to configure /etc/hosts
可以检查eureka中注册的EngineConnManager服务的信息和报错的信息是否一致，如果不一致需要配置/etc/hosts
