### ISSUE TITLE
[Bug] BmlRestfulApi missing spaces in some log

### ISSUE THREAD

**Issue by casionone** [apache/incubator-linkis#2166]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

```
2022-05-20 15:41:58.148 [ERROR] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.e.s.s.DefaultEngineConnResourceService (91) [apply] - Failed to upload engine conn to bml, now exit! org.apach
e.linkis.httpclient.exception.HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/updateVersion request failed! ResponseBody is {"method":null,"status":1,"message":"error
code(错误码): 78361, error message(错误信息): resourceId: 1d001f73-7d65-42ca-9c7e-205f271f404ais Null, illegal, or deleted!.","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","leve
l":2,"port":9105,"errCode":78361,"ip":"bdpdev01dss03","desc":"resourceId: 1d001f73-7d65-42ca-9c7e-205f271f404ais Null, illegal, or deleted!"}}}. errCode: 10905 ,desc: URL /api/rest_j/v1/bml/u
pdateVersion request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 78361, error message(错误信息): resourceId: 1d001f73-7d65-42ca-9c7e-205f271f404ais Null,
illegal, or deleted!.","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":78361,"ip":"bdpdev01dss03","desc":"resourceId: 1d001f73-7d65-42ca-9c7e-205f2
71f404ais Null, illegal, or deleted!"}}}. ,ip: bdpdev01dss02 ,port: 9103 ,serviceKind: linkis-cg-engineplugin ,ip: bdpdev01dss02 ,port: 9103 ,serviceKind: linkis-cg-engineplugin
        at org.apache.linkis.httpclient.dws.response.DWSResult$$anonfun$set$2.apply(DWSResult.scala:77) ~[linkis-gateway-httpclient-support-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.dws.response.DWSResult$$anonfun$set$2.apply(DWSResult.scala:75) ~[linkis-gateway-httpclient-support-1.1.2.jar:1.1.2]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:53) ~[linkis-common-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.dws.response.DWSResult$class.set(DWSResult.scala:75) ~[linkis-gateway-httpclient-support-1.1.2.jar:1.1.2]
        at org.apache.linkis.bml.response.BmlResult.set(BmlResult.scala:26) ~[linkis-bml-client-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$2.apply(DWSHttpClient.scala:70) ~[linkis-gateway-httpclient-support-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$2.apply(DWSHttpClient.scala:66) ~[linkis-gateway-httpclient-support-1.1.2.jar:1.1.2]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.12.jar:?]
        at org.apache.linkis.httpclient.dws.DWSHttpClient.httpResponseToResult(DWSHttpClient.scala:66) ~[linkis-gateway-httpclient-support-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.AbstractHttpClient.responseToResult(AbstractHttpClient.scala:425) ~[linkis-httpclient-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:126) ~[linkis-httpclient-1.1.2.jar:1.1.2]
        at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:92) ~[linkis-httpclient-1.1.2.jar:1.1.2]
```
`resourceId: 1d001f73-7d65-42ca-9c7e-205f271f404ais Null, illegal, or deleted!`  
->
`resourceId: 1d001f73-7d65-42ca-9c7e-205f271f404a is Null, illegal, or deleted!`  

### Relevent platform

None

### Reproduction script

None

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by casionone** [comment]
I want to fix this issue,you can assign it to me.
