### ISSUE TITLE
Spark scala job failed

### ISSUE THREAD

**Issue by peniridis** [apache/incubator-linkis#219]
**Describe the bug**
spark scala job failed.
YARN Application Attempts log.

描述错误
一个作业失败。
纱线应用尝试日志
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/hadoop/yarn/local/filecache/10/spark2-hdp-yarn-archive.tar.gz/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/3.0.1.0-187/hadoop/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
19/12/19 11:08:36 INFO util.SignalUtils: Registered signal handler for TERM
19/12/19 11:08:36 INFO util.SignalUtils: Registered signal handler for HUP
19/12/19 11:08:36 INFO util.SignalUtils: Registered signal handler for INT
19/12/19 11:08:36 INFO spark.SecurityManager: Changing view acls to: yarn,hdfs
19/12/19 11:08:36 INFO spark.SecurityManager: Changing modify acls to: yarn,hdfs
19/12/19 11:08:36 INFO spark.SecurityManager: Changing view acls groups to: 
19/12/19 11:08:36 INFO spark.SecurityManager: Changing modify acls groups to: 
19/12/19 11:08:36 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(yarn, hdfs); groups with view permissions: Set(); users  with modify permissions: Set(yarn, hdfs); groups with modify permissions: Set()
19/12/19 11:08:37 WARN conf.Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.resource.memory-mb;  Ignoring.
19/12/19 11:08:37 WARN conf.Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.resource.memory-mb;  Ignoring.
19/12/19 11:08:37 INFO yarn.ApplicationMaster: Preparing Local resources
19/12/19 11:08:38 WARN conf.Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.resource.memory-mb;  Ignoring.
19/12/19 11:08:38 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1576484390235_0032_000001
19/12/19 11:08:38 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
19/12/19 11:08:38 ERROR yarn.ApplicationMaster: Uncaught exception: 
java.lang.ClassNotFoundException: com.webank.wedatasphere.linkis.engine.DataWorkCloudEngineApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.deploy.yarn.ApplicationMaster.startUserApplication(ApplicationMaster.scala:715)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:491)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:345)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$2.apply$mcV$sp(ApplicationMaster.scala:260)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$2.apply(ApplicationMaster.scala:260)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$2.apply(ApplicationMaster.scala:260)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$5.run(ApplicationMaster.scala:815)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:814)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:259)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:839)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
19/12/19 11:08:38 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Uncaught exception: java.lang.ClassNotFoundException: com.webank.wedatasphere.linkis.engine.DataWorkCloudEngineApplication)
19/12/19 11:08:38 INFO util.ShutdownHookManager: Shutdown hook called
```
and spark entrance log
```
2019-12-19 11:06:01.376 WARN  [IDE_hdfsConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 51 warn - This executor of job(IDE_hdfs_4) in starting status,When kill job need to interrupter consumer Future
2019-12-19 11:06:01.376 INFO  [IDE_hdfsConsumerThread] com.webank.wedatasphere.linkis.scheduler.future.BDPFutureTask 42 info - Start to interrupt BDPFutureTask
2019-12-19 11:06:01.376 INFO  [IDE_hdfsConsumerThread] com.webank.wedatasphere.linkis.scheduler.future.BDPFutureTask 42 info - Finished to interrupt BDPFutureTask of IDE_hdfsConsumerThread
2019-12-19 11:06:01.377 INFO  [IDE_hdfsConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 42 info - IDE_hdfs_4 change state Scheduled => Failed.
2019-12-19 11:06:01.540 INFO  [IDE_hdfsConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 239 close - job:IDE_hdfs_4 is closing
2019-12-19 11:06:01.542 INFO  [sparkEntrance-EventListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.EntranceWebSocketService 209 apply -  retMessage: execID is 030522IDEsparkwormhole.hdp.com:10002IDE_hdfs_4, status is Failed, websocketTag is a28635e080437bedbf135b6ddb7a21cc
2019-12-19 11:06:01.542 INFO  [IDE_hdfsConsumerThread] com.webank.wedatasphere.linkis.entrance.job.EntranceExecutionJob 47 info - IDE_hdfs_4 execute failed. Reason: Request engine failed, possibly due to insufficient resources or background process error com.webank.wedatasphere.linkis.entrance.exception.EntranceErrorException: errCode: 20010 ,desc: EngineManagerErrorException: errCode: 20019 ,desc: init engine failed! Unknown error, please ask admin for help. ,ip: wormhole.hdp.com ,port: 10001 ,serviceKind: sparkEngineManager ,ip: wormhole.hdp.com ,port: 10002 ,serviceKind: sparkEntrance
```

**To Reproduce**
1. I modified the package com.webank.wedatasphere.linkis.enginemanager.process line 
```
    this.master("yarn")
    this.deployMode("cluster") // it was 「client」, i don't want to submit to local driver
```
2. run the script by DSS
3. the host only left 500m memery
4. so this is  indeed insufficient resources?

**复现**
重现行为的步骤：
1.我修改了com.webank.wedatasphere.linkis.enginemanager.processline包
```
this.master("yarn");
this.deployMode（“cluster”）//它是“client”，我不想提交到本地驱动程序
```
2.通过DSS运行脚本

3.主机只剩下500m内存

4.那么这确实是资源不足吗？

**Comment by wushengyeyouya** [comment]
The root reason is that you change the client mode to cluster mode.
We don't suggest to start spark engine by cluster mode as the following reasons:
1. it is not easy to control the running job.
2. it is not easy to control the life cycle of the spark application.
3. it is inconvenient to get logs and progress of jobs.
4. The spark engine is enable with python, Scala, SQL, and R script interpreters. The driver needs amounts of memory to support execute pyspark code. Once the memory usage is excessive, it will be directly killed by YARN.

**Comment by peniridis** [comment]
```
java.lang.ClassNotFoundException: com.webank.wedatasphere.linkis.engine.DataWorkCloudEngineApplication
```
the reason and essence of the error is lack of linkis-ujes-spark-engine-0.9.1.jar on remote node,is that so? the linkis enginemanage doesn't add jars to remote host which yarn scheduled.

**Comment by peacewong** [comment]
Hello, you can refer to this PR:https://github.com/WeBankFinTech/Linkis/pull/347
