### ISSUE TITLE
Compatible with mysql8

### ISSUE THREAD

**Issue by wForget** [apache/incubator-linkis#228]
**Is your feature request related to a problem? Please describe.**
使用 mysql8.0 报错

**Describe the solution you'd like**
将 linkis-module 中 mysql-connector-java 版本设置为 5.1.46
参考：https://stackoverflow.com/questions/50177907/com-mysql-jdbc-exceptions-jdbc4-mysqlnontransientconnectionexception-could-not

**Describe alternatives you've considered**
no

**Additional context**
no

您的功能请求是否与问题有关？请描述一下。
使用 mysql8.0版报错
描述您想要的解决方案
将 linkis模块中 mysql连接器java版本设置为 5.1.46
参考：https://stackoverflow.com/questions/50177907/com-mysql-jdbc-exceptions-jdbc4-mysqlnontransientconnectionexception-could-not
描述你考虑过的备选方案
不
附加上下文
不

**Comment by wForget** [comment]
![error](https://user-images.githubusercontent.com/17894939/71409202-ab00a300-267b-11ea-953b-14427825064e.png)

**Comment by wForget** [comment]
```
2019-12-24 18:28:51.314 ERROR [main] com.webank.wedatasphere.linkis.metadata.hive.config.LinkisMybatisConfig 140 mutiDataSource - 连接数据库失败： com.mysq
l.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2311) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.34.jar:5.1.34]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
```

**Comment by peacewong** [comment]
Thank you, it seems to be compatible with the mysql8.0 version

**Comment by soybean217** [comment]
mysql 5.5 用DSS的全家桶安装也是不语句不兼容的， 实测mysql5.6是OK的。
