### ISSUE TITLE
[Bug] ClassNotFoundException: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by yongster** [apache/incubator-linkis#2595]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

我运行 
linkis-cg-enginplugin 获取不到mysql的驱动jar。我上传一依赖到 linkis/lib/linkis-engineconn-plugins/hive/dist/v3.1.2/lib后。也没有解决问题

### Relevent platform

uabntu 

### Reproduction script

start-all.sh

### Anything else

log linkis-cg-engineplugin.log
```
022-08-04 17:12:43.909 [ERROR] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.e.s.s.DefaultEngineConnResourceService (91) [$anonfun$run$4] - Failed to upload engine conn to bml, now exit! org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: com.mysql.jdbc.Driver
### The error may exist in class path resource [org/apache/linkis/engineplugin/server/dao/impl/EngineConnBmlResourceMapper.xml]
### The error may involve org.apache.linkis.engineplugin.server.dao.EngineConnBmlResourceDao.getAllEngineConnBmlResource
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: com.mysql.jdbc.Driver
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92) ~[mybatis-spring-2.0.5.jar:2.0.5]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440) ~[mybatis-spring-2.0.5.jar:2.0.5]
        at com.sun.proxy.$Proxy150.selectList(Unknown Source) ~[?:?]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223) ~[mybatis-spring-2.0.5.jar:2.0.5]
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:173) ~[mybatis-plus-core-3.4.1.jar:3.4.1]
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78) ~[mybatis-plus-core-3.4.1.jar:3.4.1]
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148) ~[mybatis-plus-core-3.4.1.jar:3.4.1]
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89) ~[mybatis-plus-core-3.4.1.jar:3.4.1]
        at com.sun.proxy.$Proxy151.getAllEngineConnBmlResource(Unknown Source) ~[?:?]
        at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.org$apache$linkis$engineplugin$server$service$DefaultEngineConnResourceService$$refresh(DefaultEngineConnResourceService.scala:137) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$3(DefaultEngineConnResourceService.scala:87) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
        at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$3$adapted(DefaultEngineConnResourceService.scala:85) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:193) ~[scala-library-2.12.15.jar:?]
        at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$2(DefaultEngineConnResourceService.scala:85) ~[linkis-engineconn-plugin-server-1.1.1.jar:1.1.1]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.15.jar:?]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.1.jar:1.1.1]
```
### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ruY9527** [comment]
Hi,please see https://linkis.apache.org/zh-CN/docs/latest/deployment/quick-deploy.
move the mysql-connector-java-5.1.49.jar to {LINKIS_HOME}/lib/linkis-spring-cloud-services/linkis-mg-gateway and  {LINKIS_HOME}/lib/linkis-commons/public-module/
