### ISSUE TITLE
[Bug] presto missing dependencies when compiling package

### ISSUE THREAD

**Issue by binbinCheng** [apache/incubator-linkis#2596]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-engineConnplugin

### What happened + What you expected to happen

linkis uses presto engine to abnormally prompt missing dependencies when executing task commands

### Relevent platform

linkis +presto

### Reproduction script

![image](https://user-images.githubusercontent.com/106590848/182818773-89d7a113-01c7-49cb-97a5-22cbe640e84a.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by binbinCheng** [comment]
2022-08-03 17:23:32.487 ERROR [ConcurrentEngineConnThreadPool1] org.apache.linkis.common.utils.Utils$ 58 error - Throw error java.lang.NoClassDefFoundError: com/facebook/airlift/json/JsonCodec
	at com.facebook.presto.client.StatementClientV1.<clinit>(StatementClientV1.java:88) ~[presto-client-0.234.jar:0.234-1f00527]
	at com.facebook.presto.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24) ~[presto-client-0.234.jar:0.234-1f00527]
	at org.apache.linkis.engineplugin.presto.executer.PrestoEngineConnExecutor.executeLine(PrestoEngineConnExecutor.scala:88) ~[linkis-engineplugin-presto-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(ComputationExecutor.scala:179) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(ComputationExecutor.scala:178) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$6.apply(ComputationExecutor.scala:180) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$6.apply(ComputationExecutor.scala:174) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at scala.collection.immutable.Range.foreach(Range.scala:160) ~[scala-library-2.11.12.jar:?]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2.apply(ComputationExecutor.scala:173) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2.apply(ComputationExecutor.scala:149) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryFinally(Utils.scala:61) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.toExecuteTask(ComputationExecutor.scala:226) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$3.apply(ComputationExecutor.scala:241) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$3.apply(ComputationExecutor.scala:241) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ConcurrentComputationExecutor.ensureOp(ConcurrentComputationExecutor.scala:49) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.execute(ComputationExecutor.scala:240) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ConcurrentComputationExecutor.execute(ConcurrentComputationExecutor.scala:39) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.presto.executer.PrestoEngineConnExecutor.execute(PrestoEngineConnExecutor.scala:78) ~[linkis-engineplugin-presto-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl.org$apache$linkis$engineconn$computation$executor$service$TaskExecutionServiceImpl$$executeTask(TaskExecutionServiceImpl.scala:298) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$3$$anonfun$run$3$$anon$4$$anonfun$run$4.apply$mcV$sp(TaskExecutionServiceImpl.scala:272) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$3$$anonfun$run$3$$anon$4$$anonfun$run$4.apply(TaskExecutionServiceImpl.scala:270) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$3$$anonfun$run$3$$anon$4$$anonfun$run$4.apply(TaskExecutionServiceImpl.scala:270) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$3$$anonfun$run$3$$anon$4.run(TaskExecutionServiceImpl.scala:273) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: com.facebook.airlift.json.JsonCodec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
	... 30 more
