### ISSUE TITLE
[Question] When I execute the SQOOP in Exchangeis to import data from MySQL to Hive, an error “Failed to create engineResource”  appears. Please help me, this problem is very urgent! Thank you very much.

### ISSUE THREAD

**Issue by qieelann** [apache/incubator-linkis#2660]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Environment name and version:
    - hive-2.3.3
    - spark-2.4.3
    - jdk 1.8.0_312
    - hadoop 2.7.2
    - linkis 1.1.1
    - dss 1.1.0
    - exchangis 1.1.0

### Describe your questions

This error occurred when I was executing the sqoop node of exchangis,. The main error information is as follows (**screenshot of Web error. I sorted the relevant log files and put them in the attachment of exchangis_sqoop_error_logs.zip**):
当我在执行exchangis的sqoop节点时，出现了这个错误，。
主要错误信息如下(**web错误截图，有关日志文件我都整理放在exchangis_sqoop_error_logs.zip这个附件了**)：

```
Caused by: org.apache.linkis.httpclient.exception.HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/linkisManager/createEngineConn request failed! ResponseBody is {"method":"/api/linkisManager/createEngineConn","status":1,"message":"Create engineConn failed, caused by AMErrorException: errCode: 30001 ,desc: Failed to create engineResource ,ip: slave4 ,port: 9101 ,serviceKind: linkis-cg-linkismanager.","data":{}}. errCode: 10905 ,desc: URL /api/rest_j/v1/linkisManager/createEngineConn request failed! ResponseBody is {"method":"/api/linkisManager/createEngineConn","status":1,"message":"Create engineConn failed, caused by AMErrorException: errCode: 30001 ,desc: Failed to create engineResource ,ip: slave4 ,port: 9101 ,serviceKind: linkis-cg-linkismanager.","data":{}}. ,ip: slave4 ,port: 8113 ,serviceKind: exchangis-server ,ip: slave4 ,port: 8113 ,serviceKind: exchangis-server
	at org.apache.linkis.httpclient.dws.response.DWSResult$$anonfun$set$2.apply(DWSResult.scala:77) ~[linkis-gateway-httpclient-support-1.1.1.jar:1.1.1]
```
[exchangis_sqoop_error_logs.zip](https://github.com/apache/incubator-linkis/files/9296122/exchangis_sqoop_error_logs.zip)

I set the JDBC parameters in the parameter settings of the management console. I also encountered a similar error when executing the JDBC script of scripts. The main error information is as follows: **the relevant logs have been sorted and packaged in linkis_ logs_ jdbc_ error.zip**
我在管理台的参数设置里设置了jdbc的参数，我在执行scriptis的jdbc脚本时也出现了类似的错误：
主要错误信息如下：**相关日志均已整理打包放在linkis_logs_jdbc_error.zip**
```
2022-08-09 18:50:35.071 [INFO ] [AskEngineService-Thread-2               ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (121) [apply] - Failed  to async(slave4:9101_0) createEngine, can Retry false org.apache.linkis.manager.am.exception.AMErrorException: errCode: 30001 ,desc: Failed to create engineResource ,ip: slave4 ,port: 9101 ,serviceKind: linkis-cg-linkismanager
	at org.apache.linkis.manager.am.pointer.DefaultEngineConnPluginPointer.createEngineResource(DefaultEngineConnPluginPointer.scala:39) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.requestResource(DefaultEngineCreateService.scala:253) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.scala:181) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:92) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:82) ~[linkis-application-manager-1.1.1.jar:1.1.1]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
```
[linkis_logs_jdbc_error.zip](https://github.com/apache/incubator-linkis/files/9296155/linkis_logs_jdbc_error.zip)

**I also sorted out my DSS_LINKIS startup log, placed on the start_logs_dss_linkis.zip, so as to prepare for you need**
**还整理了我的dss_linkis启动日志，放在了start_logs_dss_linkis.zip，以备你们需要**
[start_logs_dss_linkis.zip](https://github.com/apache/incubator-linkis/files/9296161/start_logs_dss_linkis.zip)

### Eureka service list

My Eureka Service is as follows:
我的eureka service 如下：

![image](https://user-images.githubusercontent.com/104083632/183799429-95193138-1fbf-481a-a101-9fda7bfafa7c.png)

### Some logs info or acctch file

The log file has been submitted in the text box of `Describe Your Questions`
日志文件已提交在 `Describe your questions`文本框

**Comment by ruY9527** [comment]
hi, please check lib/linkis-engineconn-plugins , whether there is a JDBC package and whether the version is correct
请检查下 lib/linkis-engineconn-plugins 是否缺少jdbc的包已经版本是否正确
![6af3a39b7c7e6e11ea9e7de6f61d908](https://user-images.githubusercontent.com/43773582/183803549-ad9def85-6170-4b29-ab63-9b0127e9af4f.png)

**Comment by casionone** [comment]
https://linkis.apache.org/zh-CN/blog/2022/04/15/how-to-download-engineconn-plugin 如何下载安装包中默认没有的引擎插件

**Comment by qieelann** [comment]
Thank you very much for your replies. The engine plug-in problem has been solved.
非常感谢各位大佬的回复，引擎插件问题已解决。

**Comment by yemengisyou** [comment]
> 

您好，请问，这个问题你是怎么解决的
