### ISSUE TITLE
[linkis-gateway]  “Connection closed prematurely”

### ISSUE THREAD

**Issue by huasir** [apache/incubator-linkis#2889]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 0.9.3
- Dss version: 0.7.0
- Environment name and version:
    - hdp-3.1.5
    - hive-3.1.0
    - jdk jdk1.8.0_241-amd64

### Describe your questions

DSS调度任务获取Jobhistory经常失败，"status":500,"error":"Internal Server Error","message":"Connection closed prematurely"

### Eureka service list

![image](https://user-images.githubusercontent.com/5368991/185537053-6e17bd5c-0fab-4062-adac-b007fea68ca6.png)

### Some logs info or acctch file

dss调度日志：
````log
19-08-2022 01:54:53 CST pd_data_agg INFO - Update Progress info:0.0
19-08-2022 01:54:53 CST pd_data_agg INFO - <----linkis log ---->
19-08-2022 01:54:53 CST pd_data_agg INFO - <----linkis log ---->
19-08-2022 01:54:56 CST pd_data_agg INFO - Update Progress info:0.0
19-08-2022 01:54:56 CST pd_data_agg INFO - <----linkis log ---->
19-08-2022 01:54:56 CST pd_data_agg INFO - <----linkis log ---->
19-08-2022 01:54:59 CST pd_data_agg INFO - Update Progress info:0.0
19-08-2022 01:54:59 CST pd_data_agg INFO - <----linkis log ---->
19-08-2022 01:54:59 CST pd_data_agg INFO - <----linkis log ---->
19-08-2022 01:55:12 CST pd_data_agg ERROR - Job run failed!
DWCException{errCode=10905, desc='URL http://10.53.11.31:9001/api/rest_j/v1/jobhistory/538219/get request failed! ResponseBody is {"timestamp":"2022-08-18T17:55:12.021+0000","path":"/api/rest_j/v1/jobhistory/538219/get","status":500,"error":"Internal Server Error","message":"Connection closed prematurely"}.', ip='null', port=0, serviceKind='null'}
	at com.webank.wedatasphere.linkis.httpclient.dws.response.DWSResult$class.set(DWSResult.scala:56)
	at com.webank.wedatasphere.linkis.ujes.client.response.JobInfoResult.set(JobInfoResult.scala:38)
	at com.webank.wedatasphere.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$1.apply(DWSHttpClient.scala:66)
	at com.webank.wedatasphere.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$1.apply(DWSHttpClient.scala:62)
	at scala.Option.map(Option.scala:146)
	at com.webank.wedatasphere.linkis.httpclient.dws.DWSHttpClient.httpResponseToResult(DWSHttpClient.scala:62)
	at com.webank.wedatasphere.linkis.httpclient.AbstractHttpClient.responseToResult(AbstractHttpClient.scala:222)
	at com.webank.wedatasphere.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:96)
	at com.webank.wedatasphere.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:87)
	at com.webank.wedatasphere.linkis.ujes.client.UJESClientImpl.executeUJESJob(UJESClientImpl.scala:34)
	at com.webank.wedatasphere.linkis.ujes.client.UJESClient.getJobInfo(UJESClient.scala:74)
	at com.webank.wedatasphere.dss.linkis.node.execution.execution.impl.LinkisNodeExecutionImpl.waitForComplete(LinkisNodeExecutionImpl.java:133)
	at com.webank.wedatasphere.dss.plugins.azkaban.linkis.jobtype.AzkabanDssJobType.run(AzkabanDssJobType.java:97)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:813)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:602)
	at azkaban.execapp.JobRunner.run(JobRunner.java:563)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19-08-2022 01:55:12 CST pd_data_agg ERROR - errCode: 10905 ,desc: URL http://10.53.11.31:9001/api/rest_j/v1/jobhistory/538219/get request failed! ResponseBody is {"timestamp":"2022-08-18T17:55:12.021+0000","path":"/api/rest_j/v1/jobhistory/538219/get","status":500,"error":"Internal Server Error","message":"Connection closed prematurely"}. ,ip: null ,port: 0 ,serviceKind: null cause: null
19-08-2022 01:55:12 CST pd_data_agg INFO - Finishing job pd_data_agg at 1660845312030 with status FAILED
````

linkis-gateway.log:
````log
022-08-19 01:55:12.025 INFO  [reactor-http-nio-24] com.webank.wedatasphere.linkis.server.security.SSOUtils$ 42 info - add login userTicketCookie for user root.
2022-08-19 01:55:12.025 INFO  [reactor-http-nio-13] com.webank.wedatasphere.linkis.gateway.route.DefaultGatewayRouter 42 info - GatewayRouter route requestUri /api/rest_j/v1/entrance/090811schedulerappjointsl
ave3:9005scheduler_root_54442/progress with parsedService appjoint to ServiceInstance(appjointentrance, slave3:9005)
2022-08-19 01:55:12.025 INFO  [reactor-http-nio-61] com.webank.wedatasphere.linkis.server.security.SSOUtils$ 42 info - add login userTicketCookie for user root.
2022-08-19 01:55:12.025 INFO  [reactor-http-nio-11] com.webank.wedatasphere.linkis.gateway.route.DefaultGatewayRouter 42 info - GatewayRouter route requestUri /api/rest_j/v1/entrance/090811schedulerappjointsl
ave3:9005scheduler_root_54435/progress with parsedService appjoint to ServiceInstance(appjointentrance, slave3:9005)
2022-08-19 01:55:12.025 INFO  [reactor-http-nio-20] com.webank.wedatasphere.linkis.gateway.route.DefaultGatewayRouter 42 info - GatewayRouter route requestUri /api/rest_j/v1/entrance/090811schedulerappjointsl
ave3:9005scheduler_root_54432/progress with parsedService appjoint to ServiceInstance(appjointentrance, slave3:9005)
2022-08-19 01:55:12.022 ERROR [reactor-http-nio-9] org.springframework.boot.autoconfigure.web.reactive.error.DefaultErrorWebExceptionHandler 218 log - Failed to handle request [GET http://10.53.11.31:9001/api/rest_j/v1/jobhistory/538219/get] java.io.IOException: Connection closed prematurely
        at reactor.ipc.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:269) [reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
        at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:113) [reactor-netty-0.7.8.RELEASE.jar:0.7.8.RELEASE]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [netty-codec-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [netty-codec-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282) [netty-codec-http-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar:4.1.25.Final]
````

**Comment by utopianet** [comment]
建议升级使用最新稳定版1.1.3:
It is recommended to upgrade and use the latest stable version 1.1.3:
https://github.com/apache/incubator-linkis/releases
