### ISSUE TITLE
[Question][Hive Engine] Calling recordValidTxn() more than once in the same txnid

### ISSUE THREAD

**Issue by mowenfuhua123** [apache/incubator-linkis#2918]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - hdp-3.1.0
    - hive-3.1.0
    - spark-2.4.3
    - scala-2.11.12
    - jdk 1.8.0_161-b14
    - ....

### Describe your questions

Q1.  ...
在dss中使用hive建表语法
create  table test_78 as 
select
*
from 
****.***; 
时候报错，在后台用hive 登录执行以上语句正常执行。
![1661137492880](https://user-images.githubusercontent.com/55682410/185830603-06d096e6-a28f-4db9-aab3-2fcacb9d9546.png)

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)
![1661137613549](https://user-images.githubusercontent.com/55682410/185830906-2f3cf82e-8692-45e7-b5a8-d3a1298107f7.png)
![1661137625312](https://user-images.githubusercontent.com/55682410/185830939-c5dd1a47-c8ee-49d1-867d-ba0715ec5d02.png)

### Some logs info or acctch file

linkis-xxx.log:
````log
 ERROR [Linkis-Default-Scheduler-Thread-19] org.apache.hadoop.hive.ql.Driver 1247 printError - FAILED: Error in acquiring locks: calling recordValidTxn() more than once in the same txnid:705363368
java.lang.IllegalStateException: calling recordValidTxn() more than once in the same txnid:705363368
	at org.apache.hadoop.hive.ql.Driver.acquireLocks(Driver.java:1614)
	at org.apache.hadoop.hive.ql.Driver.lockAndRespond(Driver.java:1795)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1965)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1709)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1703)
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:157)
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.linkis.engineplugin.hive.executor.HiveDriverProxy.run(HiveEngineConnExecutor.scala:523)
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor.org$apache$linkis$engineplugin$hive$executor$HiveEngineConnExecutor$$executeHQL(HiveEngineConnExecutor.scala:195)
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anon$1.run(HiveEngineConnExecutor.scala:146)
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anon$1.run(HiveEngineConnExecutor.scala:139)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor.executeLine(HiveEngineConnExecutor.scala:139)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$10$$anonfun$apply$11.apply(ComputationExecutor.scala:183)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$10$$anonfun$apply$11.apply(ComputationExecutor.scala:182)
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$10.apply(ComputationExecutor.scala:184)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2$$anonfun$apply$10.apply(ComputationExecutor.scala:178)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2.apply(ComputationExecutor.scala:177)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$toExecuteTask$2.apply(ComputationExecutor.scala:153)
	at org.apache.linkis.common.utils.Utils$.tryFinally(Utils.scala:61)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.toExecuteTask(ComputationExecutor.scala:230)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$3.apply(ComputationExecutor.scala:245)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor$$anonfun$3.apply(ComputationExecutor.scala:245)
	at org.apache.linkis.common.utils.Utils$.tryFinally(Utils.scala:61)
	at org.apache.linkis.engineconn.acessible.executor.entity.AccessibleExecutor.ensureIdle(AccessibleExecutor.scala:55)
	at org.apache.linkis.engineconn.acessible.executor.entity.AccessibleExecutor.ensureIdle(AccessibleExecutor.scala:49)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.ensureOp(ComputationExecutor.scala:137)
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.execute(ComputationExecutor.scala:244)
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl.org$apache$linkis$engineconn$computation$executor$service$TaskExecutionServiceImpl$$executeTask(TaskExecutionServiceImpl.scala:296)
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$2$$anonfun$run$2.apply$mcV$sp(TaskExecutionServiceImpl.scala:229)
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$2$$anonfun$run$2.apply(TaskExecutionServiceImpl.scala:227)
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$2$$anonfun$run$2.apply(TaskExecutionServiceImpl.scala:227)
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40)
	at org.apache.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:69)
	at org.apache.linkis.engineconn.computation.executor.service.TaskExecutionServiceImpl$$anon$2.run(TaskExecutionServiceImpl.scala:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)
[err.log](https://github.com/apache/incubator-linkis/files/9390987/err.log)

**Comment by casionone** [comment]
Does it happen every time?
Is there any useful information I can get from here? https://www.mail-archive.com/issues@hive.apache.org/msg116947.html
