### ISSUE TITLE
linkis-resourcemanager start fail !

### ISSUE THREAD

**Issue by zhuchengwen** [apache/incubator-linkis#312]
2020-02-26 18:01:29,120 INFO  (main) INFO log - Logging initialized @5868ms
2020-02-26 18:01:29,215 INFO  (main) INFO JettyServletWebServerFactory - Server initialized with port: 9104
2020-02-26 18:01:29,285 WARN  (main) WARN AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.NoSuchFieldError: GIT_HASH
2020-02-26 18:01:29,302 INFO  (main) INFO ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-02-26 18:01:29,305 ERROR (main) ERROR SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.NoSuchFieldError: GIT_HASH
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:105)
Caused by: java.lang.NoSuchFieldError: GIT_HASH
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:107)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:85)
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:409)
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:153)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152)
	... 6 more

**Comment by 77954309** [comment]
这是因为jetty包冲突，我当初解决方案，mv 一个包（jetty-util-9.3.19.v20170502.jar.bak），保留一个jetty-util
