### ISSUE TITLE
[Question] MetaException: Could not connect to meta store using any of the URIs provided. Most recent failure

### ISSUE THREAD

**Issue by stvlllll** [apache/incubator-linkis#3122]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - hdp-2.7.2
    - hive-2.3.3
    - spark-2.4.3

### Describe your questions

Scripts执行脚本报错

### Some logs info or acctch file

2022-08-29 16:53:01.053 INFO Program is substituting variables for you
2022-08-29 16:53:01.053 INFO Variables substitution ended successfully
2022-08-29 16:53:01.053 WARN You submitted a sql without limit, DSS will add limit 5000 to your sql
2022-08-29 16:53:01.053 INFO SQL code check has passed
Job with jobId : IDE_hadoop_hive_4 and execID : IDE_hadoop_hive_4 submitted 
2022-08-29 16:53:01.053 INFO You have submitted a new job, script code (after variable substitution) is
************************************SCRIPT CODE************************************
hadoop_indsznb_testsznb_testselect * from sznb_test.t_test limit 5000
************************************SCRIPT CODE************************************
2022-08-29 16:53:01.053 INFO Your job is accepted,  jobID is exec_id018013linkis-cg-entranceidigital:9104IDE_hadoop_hive_4 and taskID is 131 in ServiceInstance(linkis-cg-entrance, idigital:9104). Please wait it to be scheduled
job is scheduled.
2022-08-29 16:53:01.053 INFO Your job is Scheduled. Please wait it to run.
Your job is being scheduled by orchestrator.
2022-08-29 16:53:01.053 INFO job is running.
2022-08-29 16:53:01.053 INFO Your job is Running now. Please wait it to complete.
2022-08-29 16:53:01.053 INFO Job with jobGroupId : 131 and subJobId : 130 was submitted to Orchestrator.
2022-08-29 16:53:01.053 INFO Background is starting a new engine for you,execId astJob_66_codeExec_66 mark id is mark_66, it may take several seconds, please wait
2022-08-29 16:53:24.053 ERROR Job with execId-IDE_hadoop_hive_4 + subJobId : 130  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: idigital:9101_59 Failed  to async get EngineNode AMErrorException: errCode: 30002 ,desc: ServiceInstance(linkis-cg-engineconn, idigital:43968) ticketID:c9e3e031-11c8-4418-aa69-c7372ffee958 初始化引擎失败,原因: ServiceInstance(linkis-cg-engineconn, idigital:43968): log dir: /appcom/tmp/hadoop/20220829/hive/c9e3e031-11c8-4418-aa69-c7372ffee958/logs,MetaException: Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:420)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:236)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)
	at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConnSession(HiveEngineConnFactory.scala:96)
	at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConnSession(HiveEngineConnFactory.scala:43)
	at org.apache.linkis.manager.engineplugin.common.creation.AbstractEngineConnFactory$class.createEngineConn(EngineConnFactory.scala:48)
	at org.apache.linkis.engineplugin.hive.creation.HiveEngineConnFactory.createEngineConn(HiveEngineConnFactory.scala:43)
	at org.apache.linkis.engineconn.core.engineconn.DefaultEngineConnManager.createEngineConn(EngineConnManager.scala:45)
	at org.apache.linkis.engineconn.launch.EngineConnServer$.main(EngineConnServer.scala:64)
	at org.apache.linkis.engineconn.launch.EngineConnServer.main(EngineConnServer.scala)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 21 more
 ,ip: idigital ,port: 9101 ,serviceKind: linkis-cg-linkismanager ,ip: idigital ,port: 9104 ,serviceKind: linkis-cg-entrance 
 
2022-08-29 16:53:24.053 INFO job is completed.
2022-08-29 16:53:24.053 INFO Task creation time(任务创建时间): 2022-08-29 16:53:01, Task scheduling time(任务调度时间): 2022-08-29 16:53:01, Task start time(任务开始时间): 2022-08-29 16:53:01, Mission end time(任务结束时间): 2022-08-29 16:53:24
2022-08-29 16:53:24.053 INFO Your mission(您的任务) 131 The total time spent is(总耗时时间为): 23.1 秒
2022-08-29 16:53:24.053 INFO Sorry. Your job completed with a status Failed. You can view logs for the reason.

**Comment by ruY9527** [comment]
--
你好,这个超时的问题,看起来像是hive的配置什么有超时?单独使用hive去执行有这个错误吗?
 Hello, this timeout problem looks like hive's configuration. What is timeout? Is there an error in using hive alone to execute?
