### ISSUE TITLE
 从 @YARN_RESTFUL_URL 获取主Yarn resourcemanager异常

### ISSUE THREAD

**Issue by cipay0325** [apache/incubator-linkis#3195]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-6.3.0 
    - hive-2.1.1
    - spark-2.4.0
    - scala-2.12.13
    - jdk 1.8.0_181
    - ....

### Describe your questions

Q1.  ...
2022-09-01 16:56:38.056 ERROR Job with execId-IDE_root_spark_0 + subJobId : 7  execute failed,21304, Task is Failed,errorMsg: errCode: 12003 ,desc: hadoop-test-10-10-6-101:9101_0 Failed  to async get EngineNode MatchError: LinkisException{errCode=11006, desc='Failed to request external resourceRMErrorException: errCode: 11007 ,desc: Get active Yarn resourcemanager from : @YARN_RESTFUL_URL exception.(从 @YARN_RESTFUL_URL 获取主Yarn resourcemanager异常) ,ip: hadoop-test-10-10-6-101 ,port: 9101 ,serviceKind: linkis-cg-linkismanager', ip='hadoop-test-10-10-6-101', port=9101, serviceKind='linkis-cg-linkismanager'} (of class org.apache.linkis.manager.common.exception.RMErrorException) ,ip: hadoop-test-10-10-6-101 ,port: 9104 ,serviceKind: linkis-cg-entrance

### Eureka service list

![image](https://user-images.githubusercontent.com/37971707/187877531-8503174a-3326-4819-9892-c0d3aa1a21d9.png)

 

### Some logs info or acctch file

 
linkis-cg-linkismanager.log
```
o.a.l.m.a.s.e.DefaultEngineAskEngineService (123) [apply] - Task: 7 Failed  to async(hadoop-test-10-10-6-101:9101_0) createEngine, can Retry false scala.MatchError: LinkisException{errCode=11006, desc='Failed to request external resourceRMErrorException: errCode: 11007 ,desc: Get active Yarn resourcemanager from : @YARN_RESTFUL_URL exception.(从 @YARN_RESTFUL_URL 获取主Yarn resourcemanager异常) ,ip: hadoop-test-10-10-6-101 ,port: 9101 ,serviceKind: linkis-cg-linkismanager', ip='hadoop-test-10-10-6-101', port=9101, serviceKind='linkis-cg-linkismanager'} (of class org.apache.linkis.manager.common.exception.RMErrorException)
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager$$anonfun$requestResource$3$$anonfun$apply$5$$anonfun$apply$6.apply(DefaultResourceManager.scala:230) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager$$anonfun$requestResource$3$$anonfun$apply$5$$anonfun$apply$6.apply(DefaultResourceManager.scala:230) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:53) ~[linkis-common-1.1.3.jar:1.1.3]
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager$$anonfun$requestResource$3$$anonfun$apply$5.apply(DefaultResourceManager.scala:230) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager$$anonfun$requestResource$3$$anonfun$apply$5.apply(DefaultResourceManager.scala:223) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[scala-library-2.11.12.jar:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[scala-library-2.11.12.jar:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.12.jar:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.11.12.jar:?]
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager$$anonfun$requestResource$3.apply(DefaultResourceManager.scala:223) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager$$anonfun$requestResource$3.apply(DefaultResourceManager.scala:210) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.common.utils.Utils$.tryFinally(Utils.scala:61) ~[linkis-common-1.1.3.jar:1.1.3]
        at org.apache.linkis.resourcemanager.service.impl.DefaultResourceManager.requestResource(DefaultResourceManager.scala:284) ~[linkis-resource-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.requestResource(DefaultEngineCreateService.scala:261) ~[linkis-application-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.scala:183) ~[linkis-application-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:94) ~[linkis-application-manager-1.1.3.jar:1.1.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:84) ~[linkis-application-manager-1.1.3.jar:1.1.3]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]

```
log file:
  
[linkis-cg-linkismanager.log](https://github.com/apache/incubator-linkis/files/9468522/linkis-cg-linkismanager.log)

**Comment by casionone** [comment]
`@YARN_RESTFUL_URL`   yarn address configuration not be set

you can refer to 
https://linkis.apache.org/zh-CN/docs/1.2.0/deployment/quick-deploy#81-yarn%E9%98%9F%E5%88%97%E6%A3%80%E6%9F%A5
