### ISSUE TITLE
[Bug] Linkis1.1.3 calls hive2.1.1-cdh6.3.2 to use the hive2.1.1 plugin, and an error is reported

### ISSUE THREAD

**Issue by whiterxine** [apache/incubator-linkis#3310]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-engineconnn-plugin

### Steps to reproduce

1.The linkis-engineplugin-hive project in Linkis1.1.3 uses hive version 2.1.1-cdh6.3.2 to compile and obtain the v2.1.1-cdh6.3.2 version plugin
2.Rename the hive v2.1.1-cdh6.3.2 plugin to the hive 2.1.1 version plugin
3.The scriptis that comes with dss1.1.0 writes hsql, and the execution reports an error: 
2022-09-09 15:50:29.109 [WARN ] [SpringContextShutdownHook               ] o.a.l.e.h.e.HiveEngineConnExecutor (93) [apply] - close session failed java.lang.IllegalStateException: Shutdown in progress, cannot cancel a deleteOnExit
	at org.apache.hive.common.util.ShutdownHookManager.cancelDeleteOnExit(ShutdownHookManager.java:106) ~[hive-common-2.1.1-cdh6.3.2.jar:2.1.1-cdh6.3.2]
	at org.apache.hadoop.hive.common.FileUtils.deleteTmpFile(FileUtils.java:883) ~[hive-common-2.1.1-cdh6.3.2.jar:2.1.1-cdh6.3.2]
	at org.apache.hadoop.hive.ql.session.SessionState.deleteTmpOutputFile(SessionState.java:314) ~[hive-exec-2.1.1-cdh6.3.2.jar:2.1.1-cdh6.3.2]
	at org.apache.hadoop.hive.ql.session.SessionState.dropSessionPaths(SessionState.java:836) ~[hive-exec-2.1.1-cdh6.3.2.jar:2.1.1-cdh6.3.2]
	at org.apache.hadoop.hive.ql.session.SessionState.close(SessionState.java:1663) ~[hive-exec-2.1.1-cdh6.3.2.jar:2.1.1-cdh6.3.2]
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anonfun$close$1.apply$mcV$sp(HiveEngineConnExecutor.scala:352) ~[linkis-engineplugin-hive-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anonfun$close$1.apply(HiveEngineConnExecutor.scala:352) ~[linkis-engineplugin-hive-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor$$anonfun$close$1.apply(HiveEngineConnExecutor.scala:352) ~[linkis-engineplugin-hive-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryAndWarnMsg(Utils.scala:83) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor.close(HiveEngineConnExecutor.scala:352) ~[linkis-engineplugin-hive-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService$$anonfun$executorShutDownHook$1.apply$mcZ$sp(DefaultAccessibleService.scala:83) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService$$anonfun$executorShutDownHook$1.apply(DefaultAccessibleService.scala:82) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService$$anonfun$executorShutDownHook$1.apply(DefaultAccessibleService.scala:82) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:69) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService.executorShutDownHook(DefaultAccessibleService.scala:82) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:410) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1013) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:93) ~[spring-cloud-context-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]

2022-09-09 15:50:29.110 [INFO ] [SpringContextShutdownHook               ] o.a.l.e.h.e.HiveEngineConnExecutor (448) [killTask] - hive begins to kill job with id : By close
2022-09-09 15:50:29.110 [ERROR] [SpringContextShutdownHook               ] o.a.l.c.u.Utils$ (58) [error] - Throw error java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hive.ql.exec.mr.HadoopJobExecHelper
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor.killTask(HiveEngineConnExecutor.scala:449) ~[linkis-engineplugin-hive-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.computation.executor.execute.ComputationExecutor.close(ComputationExecutor.scala:128) ~[linkis-computation-engineconn-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.hive.executor.HiveEngineConnExecutor.close(HiveEngineConnExecutor.scala:353) ~[linkis-engineplugin-hive-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService$$anonfun$executorShutDownHook$1.apply$mcZ$sp(DefaultAccessibleService.scala:83) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService$$anonfun$executorShutDownHook$1.apply(DefaultAccessibleService.scala:82) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService$$anonfun$executorShutDownHook$1.apply(DefaultAccessibleService.scala:82) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.common.utils.Utils$.tryAndWarn(Utils.scala:69) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineconn.acessible.executor.service.DefaultAccessibleService.executorShutDownHook(DefaultAccessibleService.scala:82) ~[linkis-accessible-executor-1.1.3.jar:1.1.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:410) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1013) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:93) ~[spring-cloud-context-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]

### Expected behavior

run hsql normally

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-6.3.2
    - hive-2.1.1-cdh6.3.2
    - spark-2.4.0
    - scala-2.11.8
    - jdk 1.8.0_181

### Anything else

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by whiterxine** [comment]
Detailed log content:
[stdout.txt](https://github.com/apache/incubator-linkis/files/9533951/stdout.txt)

**Comment by utopianet** [comment]
建议检查环境变量，以及使用beeline命令运行hql是否正常
