### ISSUE TITLE
hadoop3框架兼容问题(Hadoop3 framework compatibility issues  )

### ISSUE THREAD

**Issue by Dlimeng** [apache/incubator-linkis#360]
这个hadoop3 hive2 重新编译linkis 时，执行hive session会通过ShimLoader验证，这个不匹配，就算重新编译也会引发别的事情，编译的话就不是编译一个jar的事，官方也发现这个问题，建议升级hive，跟hadoop映射，hadoop3 hive3 重新编译linkis可以正常使用。

**Comment by peacewong** [comment]
Hello, can you provide the error message

**Comment by 77954309** [comment]
> Hello, can you provide the error message

Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.0.0-alpha2
at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:169)
at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:136)
at org.apache.hadoop.hive.shims.ShimLoader.getHadoopThriftAuthBridge(ShimLoader.java:122)
at org.apache.hadoop.hive.metastore.HiveMetaStore.main(HiveMetaStore.java:6664)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
at org.apache.hadoop.util.RunJar.main(RunJar.java:153)

**Comment by 77954309** [comment]
> Hello, can you provide the error message

这个问题在官方有，没有更好的方案。
