### ISSUE TITLE
[Question] Visualis preview failed

### ISSUE THREAD

**Issue by sunriseXDM** [apache/incubator-linkis#3626]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - hdp-3.1.4
    - hive-3.1.0
    - spark-2.3.0
    - scala-2.11.8
    - jdk 1.8.0_121

### Describe your questions

Q1.  dashboard perview failed.

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/37735647/195306489-273e078e-7be0-49ee-9166-3360707ba090.png">

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/37735647/195306432-4e9b4f7a-dc04-41b3-a09e-4aff06f97ab5.png">

### Some logs info or acctch file

visualis.log:
````log

2022-10-12 17:15:21.784 INFO  [qtp2075380660-145] com.webank.wedatasphere.dss.standard.app.sso.builder.impl.DssMsgBuilderOperationImpl 79 getBuiltMsg - Set cookies from dssMsg: {}
2022-10-12 17:15:22.143 INFO  [qtp2075380660-103] com.webank.wedatasphere.dss.standard.app.sso.builder.impl.DssMsgBuilderOperationImpl 79 getBuiltMsg - Set cookies from dssMsg: {}
2022-10-12 17:15:22.143 INFO  [qtp2075380660-259] com.webank.wedatasphere.dss.standard.app.sso.builder.impl.DssMsgBuilderOperationImpl 79 getBuiltMsg - Set cookies from dssMsg: {}
2022-10-12 17:15:22.143 INFO  [qtp2075380660-102] com.webank.wedatasphere.dss.standard.app.sso.builder.impl.DssMsgBuilderOperationImpl 79 getBuiltMsg - Set cookies from dssMsg: {}
2022-10-12 17:15:22.144 INFO  [qtp2075380660-260] com.webank.wedatasphere.dss.standard.app.sso.builder.impl.DssMsgBuilderOperationImpl 79 getBuiltMsg - Set cookies from dssMsg: {}
2022-10-12 17:15:22.145 INFO  [qtp2075380660-103] edp.davinci.core.inteceptor.CurrentUserMethodArgumentResolver 71 resolveArgument - Get request access user name: hadoop
2022-10-12 17:15:22.146 INFO  [qtp2075380660-102] edp.davinci.core.inteceptor.CurrentUserMethodArgumentResolver 71 resolveArgument - Get request access user name: hadoop
2022-10-12 17:15:22.146 INFO  [qtp2075380660-260] edp.davinci.core.inteceptor.CurrentUserMethodArgumentResolver 71 resolveArgument - Get request access user name: hadoop
2022-10-12 17:15:22.146 ERROR [qtp2075380660-259] edp.davinci.core.config.RestExceptionHandler 53 commonExceptionHandler - Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "NaN"
2022-10-12 17:15:22.147 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 29 doBefore - ============================= start ================================
2022-10-12 17:15:22.147 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 29 doBefore - ============================= start ================================
2022-10-12 17:15:22.147 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 32 doBefore - URL      :http://c0:9703/api/rest_s/v1/visualis/projects/313
2022-10-12 17:15:22.147 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 32 doBefore - URL      :http://c0:9703/api/rest_s/v1/visualis/widgets
2022-10-12 17:15:22.147 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 42 doBefore - Method  :ProjectController.getProjectInfo
2022-10-12 17:15:22.147 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 42 doBefore - Method  :WidgetController.getWidgets
2022-10-12 17:15:22.147 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 29 doBefore - ============================= start ================================
2022-10-12 17:15:22.148 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :id,Value   :313
2022-10-12 17:15:22.148 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :projectId,Value   :313
2022-10-12 17:15:22.148 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 32 doBefore - URL      :http://c0:9703/api/rest_s/v1/visualis/dashboard/1/preview
2022-10-12 17:15:22.148 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :user,Value   :User(id=1, email=null, admin=true, active=false, name=hadoop, description=null, department=null, avatar=null, createTime=Fri Sep 09 14:46:34 CST 2022, createBy=0, updateTime=Fri Sep 09 14:46:34 CST 2022, updateBy=0)
2022-10-12 17:15:22.148 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 42 doBefore - Method  :DashboardPreviewController.previewDisplay
2022-10-12 17:15:22.148 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :request,Value   :Request(GET //c0:9703/api/rest_s/v1/visualis/widgets?projectId=313&labelsRoute=dev)@4bb04374
2022-10-12 17:15:22.148 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :id,Value   :1
2022-10-12 17:15:22.148 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :username,Value   :null
2022-10-12 17:15:22.149 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :user,Value   :User(id=1, email=null, admin=true, active=false, name=hadoop, description=null, department=null, avatar=null, createTime=Fri Sep 09 14:46:34 CST 2022, createBy=0, updateTime=Fri Sep 09 14:46:34 CST 2022, updateBy=0)
2022-10-12 17:15:22.148 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :user,Value   :User(id=1, email=null, admin=true, active=false, name=hadoop, description=null, department=null, avatar=null, createTime=Fri Sep 09 14:46:34 CST 2022, createBy=0, updateTime=Fri Sep 09 14:46:34 CST 2022, updateBy=0)
2022-10-12 17:15:22.149 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :request,Value   :Request(GET //c0:9703/api/rest_s/v1/visualis/dashboard/1/preview?labelsRoute=dev)@790f2841
2022-10-12 17:15:22.149 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :request,Value   :Request(GET //c0:9703/api/rest_s/v1/visualis/projects/313?labelsRoute=dev)@44f30e1d
2022-10-12 17:15:22.150 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 48 doBefore - Param   :response,Value   :com.alibaba.druid.support.http.WebStatFilter$StatHttpServletResponseWrapper@54763b10
2022-10-12 17:15:22.154 INFO  [qtp2075380660-260] edp.davinci.common.utils.ComponentFilterUtils 164 getSuffixVersion - The component does not match the version.
2022-10-12 17:15:22.154 INFO  [qtp2075380660-260] edp.davinci.common.utils.ComponentFilterUtils 152 getShortName - Get component name: widget1
2022-10-12 17:15:22.154 INFO  [qtp2075380660-260] edp.davinci.common.utils.ComponentFilterUtils 164 getSuffixVersion - The component does not match the version.
2022-10-12 17:15:22.155 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 55 doAfter - Response :<200 OK OK,{payload=[Widget(id=1, name=widget1, description=, viewId=1, projectId=313, type=1, publish=true, config={"cols":[{"name":"dt","type":"category","visualType":"string","field":{"alias":"","desc":"","useExpression":false},"format":{"formatType":"default"},"width":450,"widthChanged":false,"alreadySetWidth":true,"oldColumnCounts":3},{"name":"sp_code","type":"category","visualType":"string","field":{"alias":"","desc":"","useExpression":false},"format":{"formatType":"default"},"width":450,"widthChanged":false,"alreadySetWidth":true,"oldColumnCounts":3}],"rows":[],"metrics":[{"name":"sum(total_user_count)@Visualis@F2714CBE","type":"value","visualType":"number","agg":"sum","chart":{"id":1,"name":"pivot","title":"透视表","icon":"icon-table","coordinate":"cartesian","rules":[{"dimension":[0,9999],"metric":[0,9999]}],"data":{"cols":{"title":"列","type":"category"},"rows":{"title":"行","type":"category"},"metrics":{"title":"指标","type":"value"},"filters":{"title":"筛选","type":"all"},"color":{"title":"颜色","type":"category"}},"style":{"pivot":{"fontFamily":"PingFang SC","fontSize":"12","color":"#666","lineStyle":"solid","lineColor":"#D9D9D9","headerBackgroundColor":"#f7f7f7"}}},"field":{"alias":"","desc":"","useExpression":false},"format":{"formatType":"default"},"width":450,"widthChanged":false,"alreadySetWidth":true,"oldColumnCounts":3}],"filters":[{"name":"sp_code","type":"category","config":{"sqlModel":[{"name":"sp_code","type":"filter","value":["'1001'"],"operator":"in","sqlType":"VARCHAR"}],"filterSource":["1001"]}}],"chartStyles":{"table":{"fontFamily":"PingFang SC","fontSize":"12","color":"#666","lineStyle":"solid","lineColor":"#D9D9D9","headerBackgroundColor":"#f7f7f7","headerConfig":[],"columnsConfig":[],"leftFixedColumns":[],"rightFixedColumns":[],"headerFixed":true,"autoMergeCell":false,"bordered":true,"size":"small","withPaging":true,"pageSize":"5000","withNoAggregators":false},"spec":{}},"selectedChart":1,"data":[],"pagination":{"pageNo":1,"pageSize":5000,"withPaging":true,"totalCount":804},"renderType":"rerender","orders":[],"mode":"chart","model":{"yest":{"sqlType":"VARCHAR","visualType":"string","modelType":"category"},"dt":{"sqlType":"VARCHAR","visualType":"string","modelType":"category"},"sp_code":{"sqlType":"VARCHAR","visualType":"string","modelType":"category"},"sum(total_user_count)":{"sqlType":"DECIMAL","visualType":"number","modelType":"value"}},"controls":[],"computed":[],"cache":false,"expired":300,"autoLoadData":true,"query":{"groups":["dt","sp_code"],"aggregators":[{"column":"sum(total_user_count)","func":"sum"}],"filters":[{"name":"sp_code","type":"filter","value":["'1001'"],"operator":"in","sqlType":"VARCHAR"}],"orders":[],"pageNo":1,"pageSize":5000,"nativeQuery":false,"cache":false,"expired":300,"flush":false,"labels":{"route":"dev"}},"view":1,"contextId":"","nodeName":"","engine":""})], header={msg=Success, code=200}},[]>
2022-10-12 17:15:22.154 INFO  [qtp2075380660-102] edp.davinci.service.screenshot.ScreenshotUtil 82 screenshot - start screenshot for job: 0, and set screenshot time out second is: 1800
2022-10-12 17:15:22.155 INFO  [qtp2075380660-260] edp.davinci.aop.MethodLogAspect 56 doAfter - =============================  end  ================================
2022-10-12 17:15:22.156 INFO  [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 87 lambda$null$0 - thread for screenshot start, type: dashboard, id: 1
2022-10-12 17:15:22.156 INFO  [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 253 generatePhantomJsDriver - Generating PhantomJs driver (/data/workspace_tools/visualis-server/bin/phantomjs)...
2022-10-12 17:15:22.158 INFO  [pool-10-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 150 <init> - executable: /data/workspace_tools/visualis-server/bin/phantomjs
2022-10-12 17:15:22.158 INFO  [pool-10-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 151 <init> - port: 13226
2022-10-12 17:15:22.158 INFO  [pool-10-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 152 <init> - arguments: [--webdriver=13226, --webdriver-logfile=/data/workspace_tools/visualis-server/phantomjsdriver.log]
2022-10-12 17:15:22.158 INFO  [pool-10-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 153 <init> - environment: {}
2022-10-12 17:15:22.166 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 55 doAfter - Response :<200 OK OK,{payload=ProjectInfo(permission=ProjectPermission(sourcePermission=3, viewPermission=3, widgetPermission=3, vizPermission=3, schedulePermission=3, sharePermission=true, downloadPermission=true, isProjectMaintainer=true)), header={msg=Success, code=200}},[]>
2022-10-12 17:15:22.166 INFO  [qtp2075380660-103] edp.davinci.aop.MethodLogAspect 56 doAfter - =============================  end  ================================
2022-10-12 17:15:22.501 INFO  [Forwarding newSession on session null to remote] org.openqa.selenium.remote.ProtocolHandshake 77 createSession - Detected dialect: OSS
2022-10-12 17:15:22.831 INFO  [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 138 doScreenshot - for user hadoop getting... http://192.168.70.95:18091/dss/visualis/share.html#/share/dashboard?shareInfo=DA1C3E7DAF7EC46FDC39861F361C78B7517FC6CEF4F1ED425FFF75A2CB7527D3ABD4F0725AF12462EE9485E57D5234016D99EF545327466523BD89D72A85B608DF8AD39015BB17B9C407B3531FCE753537A6DCD28BA34B7E5B3CD279A38726D51456B5FBCAF282D3E95BEF815198FB041C37D0AEFB8D40CB8C1CA366B6417FD899A61F03801710C5C8947648890D7B57EE0B17BD25E0FB184453AB6E4522DA87B06DC1A2D769D0B0FD028378A7E58C514FE683FD999A68A0753C9C2D9B393DAF718CD4B039B883635638344A3A7FFE06C471B6327CC2113C4DE0D33DC426213DCC14FA03CDFA92358C4AF9F5E9F793DC817A71D96613404AFD67E6BAC4E66531&type=dashboard
2022-10-12 17:15:22.831 INFO  [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 141 doScreenshot - Start the screenshot and set the timeout value is 1800



...持续一段时间后



2022-10-12 17:32:29.197 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2022-10-12 17:37:29.198 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2022-10-12 17:42:29.198 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2022-10-12 17:47:29.199 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration
2022-10-12 17:51:24.669 INFO  [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 188 doScreenshot - for user hadoop finished getting http://192.168.70.95:18091/dss/visualis/share.html#/share/dashboard?shareInfo=DA1C3E7DAF7EC46FDC39861F361C78B7517FC6CEF4F1ED425FFF75A2CB7527D3ABD4F0725AF12462EE9485E57D5234016D99EF545327466523BD89D72A85B608DF8AD39015BB17B9C407B3531FCE753537A6DCD28BA34B7E5B3CD279A38726D51456B5FBCAF282D3E95BEF815198FB041C37D0AEFB8D40CB8C1CA366B6417FD899A61F03801710C5C8947648890D7B57EE0B17BD25E0FB184453AB6E4522DA87B06DC1A2D769D0B0FD028378A7E58C514FE683FD999A68A0753C9C2D9B393DAF718CD4B039B883635638344A3A7FFE06C471B6327CC2113C4DE0D33DC426213DCC14FA03CDFA92358C4AF9F5E9F793DC817A71D96613404AFD67E6BAC4E66531&type=dashboard, webdriver will quit soon
2022-10-12 17:51:24.744 ERROR [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 98 lambda$null$0 - error ScreenshotUtil.screenshot, org.openqa.selenium.TimeoutException: Expected condition failed: waiting for at least one condition to be valid: presence of element located by: By.id: headlessBrowserRenderSign || presence of element located by: By.id: WidgetExecuteFailedTag || presence of element located by: By.id: width || presence of element located by: By.id: height (tried for 1800 second(s) with 500 MILLISECONDS interval)
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231) ~[selenium-support-3.9.1.jar:?]
        at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:151) ~[visualis-server-1.0.0.jar:?]
        at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:89) ~[visualis-server-1.0.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: height
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'c0', ip: '192.168.70.95', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.49.1.el7.x86_64', java.version: '1.8.0_201'
Driver info: driver.version: unknown
        at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896) ~[selenium-support-3.9.1.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_201]
        at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1427) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1421) ~[selenium-support-3.9.1.jar:?]
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208) ~[selenium-support-3.9.1.jar:?]
        ... 7 more

2022-10-12 17:51:24.745 INFO  [pool-10-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 101 lambda$null$0 - thread for screenshot finish, type: dashboard, id: 1
2022-10-12 17:51:24.746 INFO  [qtp2075380660-102] edp.davinci.service.screenshot.ScreenshotUtil 118 screenshot - finish screenshot for job: 0
2022-10-12 17:51:24.747 ERROR [qtp2075380660-102] edp.davinci.controller.DashboardPreviewController 64 previewDisplay - Execute display failed, because image file is null.
2022-10-12 17:51:24.747 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 55 doAfter - Response :null
2022-10-12 17:51:24.748 INFO  [qtp2075380660-102] edp.davinci.aop.MethodLogAspect 56 doAfter - =============================  end  ================================

2022-10-12 17:52:29.199 INFO  [AsyncResolver-bootstrap-executor-0] com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver 43 getClusterEndpoints - Resolving eureka endpoints via configuration

````
log file:
 

[visualis.log](https://github.com/apache/incubator-linkis/files/9763754/visualis.log)
[application.txt](https://github.com/apache/incubator-linkis/files/9763761/application.txt)

**Comment by utopianet** [comment]
以下application.yml配置请使用ip
# ##################################
# 1. Visualis Service configuration
# ##################################
server:
  protocol: http
  address: xx  # server ip address
  port:  9009 # server port
  url: http://xx:8089/dss/visualis # frontend index page full path
  access:
    address: xx# frontend address
    port: 8089 # frontend port

**Comment by sunriseXDM** [comment]
> 
[application.txt](https://github.com/apache/incubator-linkis/files/9763735/application.txt)

**Comment by casionone** [comment]
check PhantomJS start successfully?

**Comment by sunriseXDM** [comment]
> check PhantomJS start successfully?

PhantomJS start successfully.
![image](https://user-images.githubusercontent.com/37735647/195755288-6a65b29a-df13-4a18-bebe-b102a21774bb.png)
