### ISSUE TITLE
cg-engineplugin微服务启动报错

### ISSUE THREAD

**Issue by mzq1312117926** [apache/incubator-linkis#3632]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.1.3
- Environment name and version:
    - cdh-6.3.2
    - hive-2.1.1
    - spark-3.1.3
    - scala-2.12.10
    - jdk 1.8.0_311
    - ....

### Describe your questions

Q1.  ...
2022-10-13 14:37:36.113 [ERROR] [Linkis-Default-Scheduler-Thread-1       ] o.a.l.e.s.s.DefaultEngineConnResourceService (91) [$anonfun$run$4] - Failed to upload engine conn to bml, now exit! org.apache.linkis.httpclient.exception.HttpClientRetryException: errCode: 10900 ,desc: The user is not logged in, please log in first, you can set a retry, message: {"method":"/api/rest_j/v1/bml/upload","status":-1,"message":"Token Authentication Failed, token: BML-AUTH，tokenUser: root, reason: errCode: 15201 ,desc: Token is not valid or stale! ,ip: xxxx ,port: 9002 ,serviceKind: linkis-mg-gateway","data":{}} ,ip: xxxx ,port: 9103 ,serviceKind: linkis-cg-engineplugin
	at org.apache.linkis.httpclient.AbstractHttpClient.addAttempt$1(AbstractHttpClient.scala:115) ~[linkis-httpclient-1.1.3.jar:1.1.3]
	at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:123) ~[linkis-httpclient-1.1.3.jar:1.1.3]
	at org.apache.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:92) ~[linkis-httpclient-1.1.3.jar:1.1.3]
	at org.apache.linkis.bml.client.impl.HttpBmlClient.uploadResource(HttpBmlClient.scala:313) ~[linkis-bml-client-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.uploadToBml(DefaultEngineConnResourceService.scala:59) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.$anonfun$refresh$6(DefaultEngineConnResourceService.scala:145) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.$anonfun$refresh$6$adapted(DefaultEngineConnResourceService.scala:141) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36) ~[scala-library-2.12.10.jar:?]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198) ~[scala-library-2.12.10.jar:?]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService.org$apache$linkis$engineplugin$server$service$DefaultEngineConnResourceService$$refresh(DefaultEngineConnResourceService.scala:141) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$3(DefaultEngineConnResourceService.scala:87) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$3$adapted(DefaultEngineConnResourceService.scala:85) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128) ~[scala-library-2.12.10.jar:?]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$2(DefaultEngineConnResourceService.scala:85) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.10.jar:?]
	at org.apache.linkis.common.utils.Utils$.tryCatch(Utils.scala:40) ~[linkis-common-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$1(DefaultEngineConnResourceService.scala:89) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.$anonfun$run$1$adapted(DefaultEngineConnResourceService.scala:82) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36) ~[scala-library-2.12.10.jar:?]
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33) ~[scala-library-2.12.10.jar:?]
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198) ~[scala-library-2.12.10.jar:?]
	at org.apache.linkis.engineplugin.server.service.DefaultEngineConnResourceService$$anon$1.run(DefaultEngineConnResourceService.scala:82) ~[linkis-engineconn-plugin-server-1.1.3.jar:1.1.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_311]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_311]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_311]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_311]

### Eureka service list

eg:![image](https://user-images.githubusercontent.com/7869972/183326205-381b4e30-c727-44ba-8197-9998da78b1e3.png)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->

````
log file:
 
[linkis-xxx.log](https://github.com/apache/incubator-linkis/files/9219529/yarn-error.log)

**Comment by casionone** [comment]
Maybe you need to pay attention to this  https://linkis.apache.org/zh-CN/docs/1.3.0/upgrade/upgrade-guide#41-token-%E9%85%8D%E7%BD%AE

**Comment by mzq1312117926** [comment]
> 也许你需要注意这个 https://linkis.apache.org/zh-CN/docs/1.3.0/upgrade/upgrade-guide#41-token-%E9%85%8D%E7%BD%AE
> 
> 还有关于mysql-connector-java-*.jar，确认是否存在 [https://linkis.apache.org/zh-CN/docs/1.3.0/deployment/quick-deploy#32-%E6%B7%BB %E5%8A%A0mysql%E9%A9%B1%E5%8A%A8%E5%8C%85](https://linkis.apache.org/zh-CN/docs/1.3.0/deployment/quick-deploy#32-%E6%B7%BB%E5%8A%A0mysql%E9%A9%B1%E5%8A%A8%E5%8C%85)

mysql的驱动没有问题，linkis_mg_gateway_auth_token这个表正常来说应该是有数据的对吗
