### ISSUE TITLE
Request engine failed

### ISSUE THREAD

**Issue by 1326017958** [apache/incubator-linkis#461]
**Describe the bug**
2020-06-24 14:23:52.023 ERROR Sorry, your job executed failed with reason: Request engine failed, possibly due to insufficient resources or background process error!

2020-06-24 14:23:52.023 ERROR Request engine failed, possibly due to insufficient resources or background process error (Request engine failed, possibly due to insufficient resources or background process error)!

2020-06-24 14:23:52.023 ERROR DWCException{errCode=20010, desc='EngineManagerErrorException: errCode: 20019 ,desc: init engine failed! Unknown error, please ask admin for help. ,ip: node1.hadoop ,port: 9107 ,serviceKind: hiveEngineManager', ip='node1.hadoop', port=9108, serviceKind='hiveEntrance'}

Running all scripts reports that the request engine failed, but all engine ports of linkis started successfully

---
**Describe the bug**
2020-06-24 14:23:52.023 ERROR Sorry, your job executed failed with reason: Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!

2020-06-24 14:23:52.023 ERROR Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!

2020-06-24 14:23:52.023 ERROR DWCException{errCode=20010, desc='EngineManagerErrorException: errCode: 20019 ,desc: init engine failed! Unknown error, please ask admin for help. ,ip: node1.hadoop ,port: 9107 ,serviceKind: hiveEngineManager', ip='node1.hadoop', port=9108, serviceKind='hiveEntrance'}

运行所有脚本都报请求引擎失败，但是linkis的所有引擎端口启动成功

**Comment by shenbinglife** [comment]
在我实验精简版的时候，同样出现类似的问题，我执行了一个Python例子。
我的版本是基于2020-07-01 master分支打包的版本。

这是控制台输出：
```
execId: 110610Python-Testpythonbogon:9110Python-Test__11, taskId: 12
Exception in thread "main" DWCException{errCode=60035, desc='资源不足，启动引擎失败', ip='null', port=0, serviceKind='null'}
	at com.webank.wedatasphere.linkis.ujes.client.response.JobInfoResult.getResultSetList(JobInfoResult.scala:76)
	at com.webank.bdp.dataworkcloud.ujes.client.UJESClientImplTestJ.main(UJESClientImplTestJ.java:60)
```

但是当我查看python引擎服务的日志，发现下面的ERROR日志

```
2020-07-01 20:20:30.996 [ERROR] [qtp1583878295-22                        ] c.w.w.l.r.RPCReceiveRestful (72) [apply] - error code(错误码): 20050, error message(错误信息): user cannot be empty.. com.webank.wedatasphere.linkis.enginemanager.exception.EngineManagerErrorException: errCode: 20050 ,desc: user cannot be 
empty. ,ip: bogon ,port: 9109 ,serviceKind: pythonEngineManager
        at com.webank.wedatasphere.linkis.enginemanager.EngineManagerReceiver.receiveAndReply(EngineManagerReceiver.scala:102) ~[linkis-ujes-enginemanager-0.9.4.jar:?]
```

我确定我的代码应该没有问题，我在代码处设置了用户信息，虽然我并不确定用户是否正确，是否要在数据库添加什么？ 
```java
JobExecuteAction hadoop = JobExecuteAction.builder().setCreator("Python-Test").addExecuteCode("1+1")
                .setEngineType(JobExecuteAction.EngineType$.MODULE$.PYTHON()).setUser("root").build();
        hadoop.setDWSVersion("v1");
        JobExecuteResult jobExecuteResult = client.execute(hadoop);
```

**Comment by Tandoy** [comment]
> 在我实验精简版的时候，同样出现类似的问题，我执行了一个Python例子。
> 我的版本是基于2020-07-01 master分支打包的版本。
> 
> 这是控制台输出：
> 
> ```
> execId: 110610Python-Testpythonbogon:9110Python-Test__11, taskId: 12
> Exception in thread "main" DWCException{errCode=60035, desc='资源不足，启动引擎失败', ip='null', port=0, serviceKind='null'}
> 	at com.webank.wedatasphere.linkis.ujes.client.response.JobInfoResult.getResultSetList(JobInfoResult.scala:76)
> 	at com.webank.bdp.dataworkcloud.ujes.client.UJESClientImplTestJ.main(UJESClientImplTestJ.java:60)
> ```
> 
> 但是当我查看python引擎服务的日志，发现下面的ERROR日志，提示user cannot be empty
> 
> ```
> 2020-07-01 20:20:30.996 [ERROR] [qtp1583878295-22                        ] c.w.w.l.r.RPCReceiveRestful (72) [apply] - error code(错误码): 20050, error message(错误信息): user cannot be empty.. com.webank.wedatasphere.linkis.enginemanager.exception.EngineManagerErrorException: errCode: 20050 ,desc: user cannot be 
> empty. ,ip: bogon ,port: 9109 ,serviceKind: pythonEngineManager
>         at com.webank.wedatasphere.linkis.enginemanager.EngineManagerReceiver.receiveAndReply(EngineManagerReceiver.scala:102) ~[linkis-ujes-enginemanager-0.9.4.jar:?]
> ```
> 
> 我确定我的代码应该没有问题，我在代码处设置了用户信息，虽然我并不确定用户是否正确，是否要在数据库添加什么？
> 
> ```java
> JobExecuteAction hadoop = JobExecuteAction.builder().setCreator("Python-Test").addExecuteCode("1+1")
>                 .setEngineType(JobExecuteAction.EngineType$.MODULE$.PYTHON()).setUser("root").build();
>         hadoop.setDWSVersion("v1");
>         JobExecuteResult jobExecuteResult = client.execute(hadoop);
> ```

使用UJESClientImplTestJ测试时用户需为Linkis部署用户
