### ISSUE TITLE
[SUPPORT]Linkis-1.0-rc1 for Hive engine test

### ISSUE THREAD

**Issue by Tandoy** [apache/incubator-linkis#699]
**Steps to reproduce the behavior:**
Use the official example LinkisClientTest

**Configuration**
![Snipaste_2021-04-02_16-27-24](https://user-images.githubusercontent.com/56899730/113397901-5a284000-93d0-11eb-96a0-c1e8b662b080.PNG)

**Expected behavior:**
for Linkis-1.0-rc1 for Hive engine test

**Environment Description:**
Linkis version : 1.0-rc1
Spark version : 2.4.0.cloudera2
Hadoop version : 2.6.0-cdh5.13.3
Hive version : 1.1.0-cdh5.13.3
Storage (HDFS/S3/GCS..) : HDFS
Running on Docker? (yes/no) :no

**Stacktrace:**
Caused by: com.webank.wedatasphere.linkis.manager.engineplugin.common.loader.exception.EngineConnPluginNotFoundException: errCode: 70063 ,desc: No plugin found, please check your configuration ,ip: dxbigdata103 ,port: 9103 ,serviceKind: linkis-cg-engineplugin
	at com.webank.wedatasphere.linkis.manager.engineplugin.manager.loaders.DefaultEngineConnPluginLoader.loadEngineConnPluginInternal(DefaultEngineConnPluginLoader.java:141) ~[linkis-engineconn-plugin-loader-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.manager.engineplugin.cache.GuavaEngineConnPluginCache.lambda$get$2(GuavaEngineConnPluginCache.java:110) ~[linkis-engineconn-plugin-cache-1.0.0-RC1.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875) ~[guava-25.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-25.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276) ~[guava-25.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) ~[guava-25.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) ~[guava-25.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-25.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870) ~[guava-25.1-jre.jar:?]
	at com.webank.wedatasphere.linkis.manager.engineplugin.cache.GuavaEngineConnPluginCache.get(GuavaEngineConnPluginCache.java:109) ~[linkis-engineconn-plugin-cache-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.manager.engineplugin.manager.loaders.CacheablesEngineConnPluginLoader.getEngineConnPlugin(CacheablesEngineConnPluginLoader.java:65) ~[linkis-engineconn-plugin-loader-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.engineplugin.server.service.DefaultEngineConnResourceFactoryService.getResourceFactoryBy(DefaultEngineConnResourceFactoryService.scala:34) ~[linkis-engineconn-plugin-server-1.0.0-RC1.jar:?]
	at com.webank.wedatasphere.linkis.engineplugin.server.service.DefaultEngineConnResourceFactoryService.createEngineResource(DefaultEngineConnResourceFactoryService.scala:44) ~[linkis-engineconn-plugin-server-1.0.0-RC1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at com.webank.wedatasphere.linkis.message.scheduler.AbstractMessageExecutor.lambda$run$5(AbstractMessageExecutor.java:127) ~[linkis-message-scheduler-1.0.0-RC1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
	... 1 more

**Comment by Tandoy** [comment]
Spark, Shell, and Python engines also report the same error

**Comment by peacewong** [comment]
You can refer to the installation documentation of ecp under [ecp doc](https://linkis.apache.org/zh-CN/docs/1.0.3/deployment/engine_conn_plugin_installation)
