### ISSUE TITLE
run qualitis, spark-entrance error

### ISSUE THREAD

**Issue by Alanmark88** [apache/incubator-linkis#717]
1、when run qualitis, error (当执行qualitis时候，报错)
RROR [qtp776011197-86604] impl.OuterExecutionServiceImpl submitRules: I/O error on POST request for "http://10.45.2.133:9001/api/rest_j/v1/entrance/execute": 400 Bad Request; nested exception is com.webank.wedatasphere.qualitis.exception.HttpRestTemplateException: 400 Bad Request
2、Manual submission (手动提交返回)
'{"method":"/api/rest_j/v1/entrance/execute","status":1,"message":"requestUri /api/rest_j/v1/entrance/execute need request parameter executeApplicationName","data":{}}
3、look at spark-entrance log(查看spark-entrance日志)
2021-05-08 16:42:55.537 [ERROR] [qtp931163110-32                         ] c.w.w.l.s.r.RestfulCatchAOP (72) [apply] - error code(错误码): 20050, error message(错误信息): Variable replacement failed!(变量替换失败！)NullPointerException: . com.webank.wedatasphere.linkis.entrance.interceptor.exception.VarSubstitutionException: errCode: 20050 ,desc: Variable replacement failed!(变量替换失败！)NullPointerException:  ,ip: SCSP00351 ,port: 9106 ,serviceKind: sparkEntrance

**Comment by peacewong** [comment]
Hello, can you provide more detailed stack information, because the root cause is NullPointerException, need to see which row caused the cause

**Comment by Alanmark88** [comment]
2021-05-10 15:19:46.541 [INFO ] [qtp931163110-2892                       ] c.w.w.l.e.r.EntranceRestfulApi (82) [execute] - Begin to get an execID
2021-05-10 15:19:46.543 [INFO ] [qtp931163110-2892                       ] c.w.w.l.e.s.DefaultEntranceServer (42) [info] - received a request: {executionCode=val prop = new java.util.Properties;
prop.setProperty("user", "griffindev");
prop.setProperty("password", "6yhn^YHN3456");
val tmp1 = spark.sql("select count(*) as myCount from smcv.zhizhu_bigdata_channel_second_signal_his where pt={yyyyMMdd}-1");
val schemas = tmp1.schema.fields.map(f => f.name).toList
val newSchemas = schemas.map(s => s.replaceAll("[()]", "")).toList
val tmp2 = tmp1.toDF(newSchemas: _*)
tmp2.selectExpr("max(myCount) as value", "'QUALITIS20210510151946452_925203' as application_id", "'Long' as result_type", "'4' as rule_id", "'2021-05-10 15:19:46' as create_time").write.mode(org.apache.spark.sql.SaveMode.Append).jdbc("jdbc:mysql://10.130.14.20:3306/griffindev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8", "qualitis_application_task_result", prop);, executeApplicationName=spark, requestApplicationName=IDE, runType=scala, umUser=admin}
2021-05-10 15:19:46.592 [ERROR] [qtp931163110-2892                       ] c.w.w.l.s.r.RestfulCatchAOP (72) [apply] - error code(错误码): 20050, error message(错误信息): Variable replacement failed!(变量替换失败！)NullPointerException: . com.webank.wedatasphere.linkis.entrance.interceptor.exception.VarSubstitutionException: errCode: 20050 ,desc: Variable replacement failed!(变量替换失败！)NullPointerException:  ,ip: SCSP00351 ,port: 9106 ,serviceKind: sparkEntrance
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor$$anonfun$apply$2.apply(VarSubstitutionInterceptor.scala:50) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor$$anonfun$apply$2.apply(VarSubstitutionInterceptor.scala:44) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$$anonfun$tryThrow$1.apply(Utils.scala:59) ~[linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$$anonfun$tryThrow$1.apply(Utils.scala:59) ~[linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:54) ~[linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryThrow(Utils.scala:58) ~[linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor.apply(VarSubstitutionInterceptor.scala:44) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.EntranceServer$$anonfun$execute$1$$anonfun$apply$mcV$sp$1.apply(EntranceServer.scala:63) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.EntranceServer$$anonfun$execute$1$$anonfun$apply$mcV$sp$1.apply(EntranceServer.scala:63) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.8.jar:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.8.jar:?]
        at com.webank.wedatasphere.linkis.entrance.EntranceServer$$anonfun$execute$1.apply$mcV$sp(EntranceServer.scala:63) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.EntranceServer$$anonfun$execute$1.apply(EntranceServer.scala:63) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.EntranceServer$$anonfun$execute$1.apply(EntranceServer.scala:63) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) ~[linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryThrow(Utils.scala:58) ~[linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.EntranceServer.execute(EntranceServer.scala:63) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.restful.EntranceRestfulApi.execute(EntranceRestfulApi.java:84) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.restful.EntranceRestfulApi$$FastClassBySpringCGLIB$$8c3306ec.invoke(<generated>) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP$$anonfun$1.apply(RestfulCatchAOP.scala:48) ~[linkis-module-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP$$anonfun$1.apply(RestfulCatchAOP.scala:48) ~[linkis-module-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.server.package$.catchMsg(package.scala:57) [linkis-module-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.server.package$.catchIt(package.scala:89) [linkis-module-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.server.restful.RestfulCatchAOP.dealResponseRestful(RestfulCatchAOP.scala:47) [linkis-module-0.9.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at com.webank.wedatasphere.linkis.entrance.restful.EntranceRestfulApi$$EnhancerBySpringCGLIB$$1cd2a0fb.execute(<generated>) [linkis-ujes-entrance-0.9.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.21.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.21.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.21.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.21.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.21.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.21.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) [jersey-server-2.21.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) [jaxrs-ri-2.21.jar:2.21.]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [jaxrs-ri-2.21.jar:2.21.]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [jaxrs-ri-2.21.jar:2.21.]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [jaxrs-ri-2.21.jar:2.21.]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215) [websocket-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at com.webank.wedatasphere.linkis.server.security.SecurityFilter.doFilter(SecurityFilter.scala:100) [linkis-module-0.9.2.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) [spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.Server.handle(Server.java:531) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
        at scala.collection.convert.Wrappers$JMapWrapperLike$$anon$2.<init>(Wrappers.scala:275) ~[scala-library-2.11.8.jar:?]
        at scala.collection.convert.Wrappers$JMapWrapperLike$class.iterator(Wrappers.scala:274) ~[scala-library-2.11.8.jar:?]
        at scala.collection.convert.Wrappers$JMapWrapper.iterator(Wrappers.scala:292) ~[scala-library-2.11.8.jar:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.8.jar:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.11.8.jar:?]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.8.jar:?]
        at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.8.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.CustomVariableUtils$.replaceCustomVar(CustomVariableUtils.scala:115) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor$$anonfun$apply$1.apply(VarSubstitutionInterceptor.scala:40) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor$$anonfun$apply$1.apply(VarSubstitutionInterceptor.scala:38) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) ~[linkis-common-0.9.2.jar:?]
        ... 119 more

etty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) [jetty-util-9.4.11.v20180605.jar:9.4.11.v20180605]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
        at scala.collection.convert.Wrappers$JMapWrapperLike$$anon$2.<init>(Wrappers.scala:275) ~[scala-library-2.11.8.jar:?]
        at scala.collection.convert.Wrappers$JMapWrapperLike$class.iterator(Wrappers.scala:274) ~[scala-library-2.11.8.jar:?]
        at scala.collection.convert.Wrappers$JMapWrapper.iterator(Wrappers.scala:292) ~[scala-library-2.11.8.jar:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.8.jar:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.11.8.jar:?]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.8.jar:?]
        at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.8.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.CustomVariableUtils$.replaceCustomVar(CustomVariableUtils.scala:115) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor$$anonfun$apply$1.apply(VarSubstitutionInterceptor.scala:40) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.entrance.interceptor.impl.VarSubstitutionInterceptor$$anonfun$apply$1.apply(VarSubstitutionInterceptor.scala:38) ~[linkis-ujes-entrance-0.9.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) ~[linkis-common-0.9.2.jar:?]
        ... 119 more
